### ISSUE TITLE
Is there any documentation on how to use extendedreport and what it includes?

### ISSUE THREAD

**Issue by rocxa** [eileenmcnaughton/nz.co.fuzion.extendedreport#10]
Great extension!

One point i have on it is that the capacity for line items doesn't appear to be included in the reporting?  

i.e. if you group line items by fee label and want to show the number of bookings vs the maximum for that line item, capacity field is left blank.

Thanks

**Comment by eileenmcnaughton** [comment]
I just added a readme with very basic documentation
