### ISSUE TITLE
Add email to Line Item Report for Participants

### ISSUE THREAD

**Issue by kngs** [eileenmcnaughton/nz.co.fuzion.extendedreport#100]
Love your extended reports!
Would it be easily possible to have email included in the line item report for participants?
Thanks, Karen

**Comment by eileenmcnaughton** [comment]
Added - it should be in the next release (or if you download from github directly you can get it now)

**Comment by kngs** [comment]
Thank you!  
I actually figured out how to do it a few days ago and was going to try my first pull request but didn't get around to it - you bet me.  I had to make another change to a core Participant Listing report to include Participant Note field so will try on that one to learn to process with Sean's great new documentation!  Thanks again!
