### ISSUE TITLE
Inclusion of email address

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.extendedreport#102]
Hi. Many thanks for this extension. It's getting me really close to the report I need to produce, including details from a price set. However I need to have email address available as a column. Is that do-able, and if so, what's required to make it available?

**Comment by Upperholme** [comment]
Aah! I think I may have it. Looking at #100

**Comment by eileenmcnaughton** [comment]
Great - I'll close this & you can re-open / add a new one if there is still an issue
