### ISSUE TITLE
Attempt to filter by contribution Date Received throws an error

### ISSUE THREAD

**Issue by Upperholme** [eileenmcnaughton/nz.co.fuzion.extendedreport#103]
I need a report that lists recent membership contributions and shows some line item data. It's all good so far, and the query generated is as follows:

Class used: CRM_Extendedreport_Form_Report_Price_Lineitemmembership

`
SELECT SQL_CALC_FOUND_ROWS GROUP_CONCAT(DISTINCT civicrm_contact.sort_name) as civicrm_contact_civicrm_contact_sort_name, GROUP_CONCAT(DISTINCT email.email) as civicrm_email_email_email, GROUP_CONCAT(DISTINCT membership.status_id) as civicrm_membership_membership_membership_status_id, GROUP_CONCAT(DISTINCT membership.start_date) as civicrm_membership_membership_start_date, GROUP_CONCAT(DISTINCT membership.end_date) as civicrm_membership_membership_end_date, GROUP_CONCAT(DISTINCT price_field_value.label) as civicrm_price_field_value_price_field_value_label  

FROM civicrm_line_item line_item 
  LEFT JOIN civicrm_price_field_value price_field_value
ON line_item.price_field_value_id = price_field_value.id

  LEFT JOIN civicrm_price_field price_field
ON line_item.price_field_id = price_field.id

      
  LEFT JOIN civicrm_membership membership
      ON line_item.entity_id = membership.id
      AND line_item.entity_table = 'civicrm_membership'
     
  LEFT JOIN civicrm_contact civicrm_contact
ON membership.contact_id = civicrm_contact.id 
  LEFT JOIN civicrm_address address
    ON address.contact_id = civicrm_contact.id
    AND address.is_primary = 1
     
  LEFT JOIN civicrm_email email
   ON email.contact_id = civicrm_contact.id
   AND email.is_primary = 1
 

WHERE ( membership.membership_type_id IN (1, 2, 3) ) AND ( membership.status_id IN (1, 2) ) AND ( price_field_value.label NOT LIKE '%(volunteer, affiliated)%' ) AND civicrm_contact.is_deleted = 0   

GROUP BY civicrm_contact.id   

ORDER BY (price_field_value.label) ASC, (price_field_value.label) ASC  

LIMIT 0, 50

`
If I try to filter the report further by Date Received I get an error: 
[nativecode=1054 ** Unknown column 'contribution.receive_date' in 'where clause']

Any pointers as to how to fix this most gratefully received.

**Comment by Upperholme** [comment]
In fact, with this report type "Extended Report - Membership Price Set Report", although Contribution fields are available on both the 'Columns' and 'Filters' tabs, they don't appear to be supported.

**Comment by eileenmcnaughton** [comment]
I've pushed up a fix to add that join in - hopefully it works

**Comment by Upperholme** [comment]
Many thanks. I'll test that and feed back.

**Comment by Upperholme** [comment]
Bingo. Thanks again.
