### ISSUE TITLE
Pivot table as widget showing filtered out results

### ISSUE THREAD

**Issue by kayliefz** [eileenmcnaughton/nz.co.fuzion.extendedreport#106]
Using a pivot table to show a count of contacts that fit the criteria. One of the criteria (is in AJA) is a single option from a select field and this select field is also being used as one of the table columns. As the data is filtered to the AJA option of that select field in the preview it only shows a single column for this. This preview shows as desired. 
![image](https://user-images.githubusercontent.com/33536863/35658992-c9a5463c-0768-11e8-9c1e-d72f3e5ea312.png)

When this pivot table is added as a widget, instead of seeing a similar outcome to the preview, all of the options from the select field now show as columns, though the filter removes data from these columns.
![image](https://user-images.githubusercontent.com/33536863/35659160-a58c2f6c-0769-11e8-8be8-961c38944ffd.png)

Is there a way that the widget can mimic the outcome that the preview was showing, and hide the columns that don't have data as they are being filtered out?

@stesi561 will take a first look?

**Comment by stesi561** [comment]
This might be a site specific issue. Investigating further.
