### ISSUE TITLE
WITH ROLLUP and ORDER BY (sorting and totaling at the same time)

### ISSUE THREAD

**Issue by twomice** [eileenmcnaughton/nz.co.fuzion.extendedreport#107]
Extended Reports provide a nice "total in the last row" feature. But when you sort by any column, that "totals" row goes away. This is presumably because the mechanism used for totaling (MySQ's "with rollup") is generally incompatible with the mechanism used for sorting (MySQL's "order by").  

It's conceivable (er, isn't it?) that a carefully written subselect could solve this problem, at least in some cases; not sure what edge cases might have trouble from that solution.

Exampe:
```
SELECT * FROM (
  SELECT category, count(*) cnt 
  FROM items
  GROUP BY category 
  WITH ROLLUP
) t
ORDER BY t.cnt;
```

Is this worth a try, or is it clearly unworkable?

**Comment by eileenmcnaughton** [comment]
It  might well work - but I have been having quite a lot of whackamole with ROLLUP & have been trying to add tests when I touch it to try to break the cycle of bouncing between breakages

**Comment by twomice** [comment]
So a PR for this should have a good bit of testing with it, yeah?

**Comment by eileenmcnaughton** [comment]
right - I've been adding unit tests to the extension & they run on the nightly - problematically they fail on a version of php / mysql that I am NOT using - see https://test.civicrm.org/job/CiviCRM-Ext-Matrix/ - they pass on one version of Ubuntu but not the other specifically around rollup code (@elenio might be going to figure that out for me)

**Comment by twomice** [comment]
So if I'm looking to make a PR for this, can you help me understand clearly what kind of tests (and how many, maybe?) I should plan to include?

**Comment by eileenmcnaughton** [comment]
Here is an existing example https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/master/tests/phpunit/Contribute/ContributionOverviewExtendedTest.php#L73

**Comment by twomice** [comment]
@eileenmcnaughton I'm looking at getting you a PR for this, but I'm facing a learning curve working out the nuances of the code. If, hypothetically, you were available to work on this, can you guess how many hours it might take you? (Even if your're not available, I'd really like to get your view on this, as a baseline for my own efforts.) Thanks!

**Comment by eileenmcnaughton** [comment]
@twomice you mean for the fix or for the test?

**Comment by twomice** [comment]
@eileenmcnaughton Both.

**Comment by eileenmcnaughton** [comment]
hmm - the test I would do first. I'm not quite sure TBH - I guess I'd say its a half day because that code is a bit scary around rollup.

**Comment by eileenmcnaughton** [comment]
For the record - with rollup 

```
Failure in api call for ReportTemplate getrows:  DB Error: unknown error
 SELECT GROUP_CONCAT(DISTINCT civicrm_contact.display_name) as civicrm_contact_civicrm_contact_display_name, GROUP_CONCAT(DISTINCT civicrm_contact.id) as civicrm_contact_civicrm_contact_contact_id, (contribution.id) as civicrm_contribution_contribution_id, GROUP_CONCAT(DISTINCT contribution.campaign_id) as civicrm_contribution_contribution_campaign_id, GROUP_CONCAT(DISTINCT contribution.receive_date) as civicrm_contribution_contribution_receive_date, COUNT(contribution.total_amount) as civicrm_contribution_contribution_total_amount_count, sum(contribution.total_amount) as civicrm_contribution_contribution_total_amount_sum, GROUP_CONCAT(DISTINCT contribution.id) as civicrm_contribution_id, GROUP_CONCAT(DISTINCT contribution.currency) as civicrm_contribution_currency  
        FROM  civicrm_contact      civicrm_contact 
              INNER JOIN civicrm_contribution contribution
                      ON civicrm_contact.id = contribution.contact_id AND contribution.is_test = 0 LEFT JOIN civicrm_phone phone
    ON phone.contact_id = civicrm_contact.id
    AND phone.is_primary = 1
     LEFT JOIN civicrm_address address
    ON address.contact_id = civicrm_contact.id
    AND address.is_primary = 1
     LEFT JOIN civicrm_email email
   ON email.contact_id = civicrm_contact.id
   AND email.is_primary = 1
 WHERE ( contribution.contribution_status_id IN (1) ) GROUP BY contribution.id  WITH ROLLUP  ORDER BY (civicrm_contribution_contribution_campaign_id) ASC  [nativecode=1221 ** Incorrect usage of CUBE/ROLLUP and ORDER BY]
```

**Comment by eileenmcnaughton** [comment]
Hmm & fixed in mysql - although perhaps not a widely used version yet

> Previously, MySQL did not allow the use of DISTINCT or ORDER BY in a query having a WITH ROLLUP option. This restriction is lifted in MySQL 8.0.12 and later. (Bug #87450, Bug #86311, Bug #26640100, Bug #26073513)

I may make it detect mysql version at some point

**Comment by twomice** [comment]
That's encouraging, at least.
