### ISSUE TITLE
Release date incorrect

### ISSUE THREAD

**Issue by wmortada** [eileenmcnaughton/nz.co.fuzion.extendedreport#110]
Just a minor issue, but one that people may find a bit confusing when they choose which version of the extension to install.

The release date for the last eight versions of the extension is listed as 17 June 2016 in the CiviCRM extensions directory.  I'm sure that they weren't all released on that day!

![screenshot-2018-4-30 extended reports civicrm](https://user-images.githubusercontent.com/13518928/39422744-960ff766-4c66-11e8-9242-6345b9d844d3.png)

**Comment by eileenmcnaughton** [comment]
lol - I don't know if I can retrospectively change then though... Although I can tag a new one with a better date

**Comment by wmortada** [comment]
Yes, I wondered about that.  Can't rewrite history!

**Comment by eileenmcnaughton** [comment]
well - I have deleted a bunch of tags to try to stop people installing old versions - I could delete more -

**Comment by eileenmcnaughton** [comment]
I think I got this - I'm gonna kill off that old 1.9 release though
