### ISSUE TITLE
What's closest to version 2.5 which no longer exists?

### ISSUE THREAD

**Issue by herbdool** [eileenmcnaughton/nz.co.fuzion.extendedreport#111]
Somehow a client got a 2.5 version on CiviCRM 4.6 but I looks like it no longer exists. I see a 1.9 that's up to CiviCRM 4.4 and then it jumps to 2.6 for CiviCRM 4.7+

**Comment by herbdool** [comment]
I see now that you had removed some releases because you're not supporting 4.6. A couple issues I've got with that approach. One, on the CiviCRM extension page some even older versions are still listed but the link to download is broken.

Two, I was creating a drush makefile to build freshly created code for a site that we suspect was hacked. Instead of opening all files to see if they were hacked I wanted to download fresh code from the sources. But I can't with this extension because the version was removed and the oldest version doesn't work with CiviCRM 4.6.

**Comment by stesi561** [comment]
@herbdool I've got a local copy of the repo with tags intact - you are after this commit:

`commit 5496f80078f77ef58c0bea79754eff9981f8c245 (tag: 2.5)`

hopefully this helps.

**Comment by herbdool** [comment]
Thank you @stesi561, this helps.

**Comment by eileenmcnaughton** [comment]
The reason I removed the tags is that when the next security release is dropped it will include a recommendation to uninstall extended reports if you are on 4.6.

**Comment by eileenmcnaughton** [comment]
Closing now - I recommend you uninstall this extension from 4.6 - it's not secure & not supported
