### ISSUE TITLE
Unable to save "ungrouped"

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#12]
I am trying to create a "detail" version of the "Line Item report for price sets" report in which each line is shown, and data isn't grouped.  When I uncheck the Group By Columns option for Contribution Status, I get the results I want but updating the report results in the Contribution Status status option still being checked.  So every time we run the report we have to uncheck the box.

**Comment by eileenmcnaughton** [comment]
Added a fix for this
