### ISSUE TITLE
Filtering section messed up

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#13]
This is based on the latest from git as of now. I don't believe this was the case from the version I first used last week.

In the one instance of the report we are using so far, the Group BY/Order By/Set Filters part of the report loses it's visual organization.  The fields aren't constrained by table cells.  This must be related to our custom fields, I think.

We have custom fields for transactions called "Old Transaction Data". These are text inputs for money values.  After the "Line Total" item, there is a toggle to show these items.  Below the toggle pane, there are all the other Contact custom data, with each item displayed inline outside of a table.  Quite a mess.  I have tried clearing the cache to no improvement.

**Comment by eileenmcnaughton** [comment]
Pretty sure my recent 'fixes' - port of fixes in 4.6 - fixed this - although I suspect I'll find it broke other things...
