### ISSUE TITLE
Filter on line item value?

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#14]
(still using Dec. 4th version)
Is there a way to filter on the line item total amount?  I have a user who wants to know all donations over $100 withing the last 7 days.  Since our donations come in along with memberships, the total contribution is often over $100 when the donation portion is only $20 or so.  So filtering on the contribution amount isn't enough.

**Comment by eileenmcnaughton** [comment]
I just added this to the master branch

**Comment by eileenmcnaughton** [comment]
hmm this is old & there is a commit against it - I'm going to assume its fixed
