### ISSUE TITLE
Limited Field availability in Pivot Data Contact Report

### ISSUE THREAD

**Issue by lesteresa** [eileenmcnaughton/nz.co.fuzion.extendedreport#149]
I'm trying to use the Pivot Data Contact Report, this is the first time I've used extended reports for anything, so not sure if I'm just misunderstanding something.

Anyway, the options available to me for Column Headers and Row Data seems rather limited and arbitrary. All of the options available to me (except one: gender) are custom fields, seems a bit odd that none of the standard contact fields are options and with the custom fields I can't find rhyme or reason as to why some have been included and others haven't.

There is a Warning Message, that may well be related:
Warning: Declaration of CRM_Extendedreport_Form_Report_ExtendedReport::generateFilterClause($field, $fieldName, $tableName) should be compatible with CRM_Report_Form::generateFilterClause($field, $fieldName) in require_once() (line 7 of /home/eaststreet/www/www/sites/default/files/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

I've double checked and it is the same with the Shoreditch Theme turned off. I'm on Civi 5.6 and Extended Reports 3.5.

I have attached 3 screenshots to show the warning and the options available in the drop downs.

Any help would be greatly appreciated.

![screenshot 2018-10-22 at 13 01 45](https://user-images.githubusercontent.com/44205958/47291693-7ff46c80-d5fc-11e8-8403-582711f473a1.png)
![screenshot 2018-10-22 at 13 02 06](https://user-images.githubusercontent.com/44205958/47291695-8387f380-d5fc-11e8-8609-b35d07ca16a0.png)
![screenshot 2018-10-22 at 13 14 53](https://user-images.githubusercontent.com/44205958/47291701-8a166b00-d5fc-11e8-998b-36342ae57c2f.png)

**Comment by eileenmcnaughton** [comment]
@lesteresa you are right the fields are rather limited & arbitrary - the one factor that is a bit less arbitrary is I think only fields with fixes sets of options have been included - but within that it's just a hard-coded list of tested fields https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/master/CRM/Extendedreport/Form/Report/Contact/Extendedcontact.php#L27

**Comment by lesteresa** [comment]
Oh ok, that makes sense as to why it's just gender from the standard fields
Just had another look through and experiment, as it is excluding some custom fields with fixed sets of options and including others. 

I think the ones it's excluding, but I want to use, are part of Multiple Entry Custom Fieldsets (tables).
Presumably, this behaviour is expected?

**Comment by eileenmcnaughton** [comment]
I think the way fields got on there was there was a request for field x (e.g gender) and similar fields were added at the same time - so it's more about the effort that has gone into solving various issues than a philisophical approach

**Comment by eileenmcnaughton** [comment]
I've done a lot of code updates & there are likely more fields there now

**Comment by eileenmcnaughton** [comment]
We have a pretty good range of row fields now, heading fields have to be a bit more restricted....
