### ISSUE TITLE
Subtotals AND details

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#15]
This may be a broader issue than just Extended Reports....

I have been sifting through the CiviReport reports as well as your Extended Reports.  Extended Reports are much more in line with what we need because almost all of our transactions are multiple line items and we need to search on line item financial types and not contribution financial types.  Yay for Extended Reports!

But what my users are asking for are a combination of Detail and Summaries.  If I "group" on Line Item Financial Types I get nice subtotals but all the detail is lost.  If I don't group I get nice sortable details but no subtotals, counts, averages, etc.

Am I missing something?  I don't see this sort of thing anywhere in CiviReports or Extended Reports.  Either it's there and I'm missing something, or it's not there (and probably for good reason).  Suggestions?

**Comment by eileenmcnaughton** [comment]
I'm going to close this as it seems to be an expression of intent - but it hasn't happened & may not so might not be important to track.

Please re-open or open new tickets if this is still 'live'
