### ISSUE TITLE
Last line of report missing when Event listing not sorted

### ISSUE THREAD

**Issue by gremble** [eileenmcnaughton/nz.co.fuzion.extendedreport#153]
We've created a report to list all the tickets and transaction IDs for an event. When the 'Sorting' tab has 'none' set under the 'Column' section two notable things happen.
* Pages cannot be turned
* reports exported as PDF or csv have the last line missing

It's easy to overcome by adding a sort order, but is most certainly a bug.

**Comment by jmcclelland** [comment]
I suspect this may vary depending on your version of CiviCRM. Using 5.3, I resolved this issue by commenting out:
```
 if ($this->_rollup) {
      //we want to be able to unset rows so here
      // $this->alterRollupRows($rows);
    }
```

The alterRollupRows call as shown above in ExtendedReport.php line 2429. I'm not really sure what ill effects it might have.
