### ISSUE TITLE
Hide columns with zero count in event pivot chart

### ISSUE THREAD

**Issue by litelo22** [eileenmcnaughton/nz.co.fuzion.extendedreport#159]
**Overview**
Add a display options to hide columns with zero count in event pivot chart

**Before:**

![imagen](https://user-images.githubusercontent.com/33427271/49720308-beeb8980-fc5f-11e8-9cba-eb9bcaaef8db.png)
![imagen](https://user-images.githubusercontent.com/33427271/49720348-d460b380-fc5f-11e8-96d9-19fa45499e3e.png)

**After:**

![imagen](https://user-images.githubusercontent.com/33427271/49720435-05d97f00-fc60-11e8-8637-71339256c10b.png)
![imagen](https://user-images.githubusercontent.com/33427271/49720460-18ec4f00-fc60-11e8-8e1b-1743057b6177.png)

**Comment by litelo22** [comment]
See the PR:
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/160

**Comment by francescbassas** [comment]
Thanks @litelo22 and @jromeraa to this improvement.

@eileenmcnaughton our trainee-students have been working on this enhancement that helps our users to focus on the relevant columns in event pivot chart.

**Comment by litelo22** [comment]
We fixed the error that occurred when saving.

**Comment by eileenmcnaughton** [comment]
I merged your fix here - closing

**Comment by litelo22** [comment]
Thank you so much, we checked the merge and works successfully.
