### ISSUE TITLE
Export doesn't use date filter

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#16]
The report Extended Report - Price Set Line Items dumps all data, not just those of the dates set in the Set Filter section.

**Comment by eileenmcnaughton** [comment]
I think I'm not replicating this one- at least not on master. Since it is old & unreplicated will close at this stage.. Please re-open or open a new one if required

**Comment by robbrandt** [comment]
The root cause of this is #32.  You run the report and can preview exactly the results you expect, but then you want to export them and click "export"; that runs the report fresh but the custom date range is no longer set and the results aren't filtered by date.
