### ISSUE TITLE
event reports include event templates in addition to events

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.extendedreport#165]
If you have any event templates, those get included in the report. Here's the event overview with a template:

![event-report-with-template](https://user-images.githubusercontent.com/4511942/50019372-676f5580-ffa0-11e8-8d19-e8c974034416.png)

The one with no participants is an event template and should be omitted.

**Comment by eileenmcnaughton** [comment]
closing as related PR was merged
