### ISSUE TITLE
RelationshipExtended report with Tag filter causes syntax error

### ISSUE THREAD

**Issue by agileware-fj** [eileenmcnaughton/nz.co.fuzion.extendedreport#167]
### Steps to reproduce:

1.  Create a new "Extended Report - Relationships" report
2. Add some columns
3. Add a Tag filter
4. Press "Preview Report"

### Expected results:

Report output is restricted to relationships where one or the other contact is tagged with the selected Tag(s)

### Actual results

"DB Error: syntax error"

### Technical details

Error code from CiviCRM.bunchofhex.log:

```[nativecode=1064 ** You have an error in your
 SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'IN (
                          SELECT DISTINCT tag_civireport.entity_id
        ' at line 17]
```

Actual SQL produced in testing:

```sql
SELECT SQL_CALC_FOUND_ROWS contact_a_civicrm_contact.display_name as contact_a_civicrm_contact_contact_a_civicrm_contact_contact_a_display_name, contact_b_civicrm_contact.display_name as contact_b_civicrm_contact_contact_b_civicrm_contact_
contact_b_display_name, relationship.start_date as civicrm_relationship_relationship_relationship_start_date, relationship.end_date as civicrm_relationship_relationship_relationship_end_date, relationship.description as civicrm_relationship_relationship_rela
tionship_description, relationship_type.label_a_b as civicrm_relationship_type_relationship_type_label_a_b , contact_a_civicrm_contact.sort_name as contact_a_civicrm_contact_contact_a_civicrm_contact_contact_a_sort_name  FROM civicrm_contact contact_a_civicr
m_contact
      INNER JOIN civicrm_relationship relationship
          ON ( relationship.contact_id_a =
          contact_a_civicrm_contact.id )

          INNER JOIN civicrm_contact contact_b_civicrm_contact
          ON ( relationship.contact_id_b =
          contact_b_civicrm_contact.id )


          LEFT JOIN civicrm_relationship rc ON (contact_b_civicrm_contact.id = rc.contact_id_a AND rc.relationship_type_id = 15)
          LEFT JOIN civicrm_relationship rccoordinator ON (contact_b_civicrm_contact.id = rccoordinator.contact_id_a AND rccoordinator.relationship_type_id = 8)
          LEFT JOIN civicrm_case case_civireport ON rccoordinator .case_id = case_civireport.id
      INNER JOIN civicrm_relationship_type relationship_type
      ON ( relationship.relationship_type_id  =
      relationship_type.id  )
     WHERE  .id IN (
                          SELECT DISTINCT tag_civireport.entity_id
                          FROM civicrm_entity_tag tag_civireport
                          WHERE entity_table = 'civicrm_contact' AND tag_civireport.tag_id IN (3) )  AND contact_a_civicrm_contact.is_deleted = 0    ORDER BY (contact_a_civicrm_contact.sort_name) ASC  LIMIT 0, 50
```

**Comment by agileware-fj** [comment]
Agileware ref is SUP-6968

**Comment by eileenmcnaughton** [comment]
thanks @agileware-fj  - I've refactored quite a lot & added tests / CI - but yeah - this might be fallout from that....

**Comment by agileware-fj** [comment]
You're welcome, @eileenmcnaughton 

When I checked the log I could see the obvious problem – missing table name – but I've no idea how to address that.  I think all the Tag stuff is inherited from the CRM_Report_Form_ExtendedReport class?

**Comment by eileenmcnaughton** [comment]
Yeah - I think so - probably something about the table db alias - basically the changes make it much more like 'generate all the right metadata about tables & columns up front & then rely on it' rather than 'use black magic to figure out stuff when you need it' - but it does rely on the 'generate all the right metadata about tables & columns up front' bit working.

I'll try to dig in

**Comment by agileware-fj** [comment]
Thanks, Eileen

**Comment by eileenmcnaughton** [comment]
should be fixed now

**Comment by agileware-fj** [comment]
Hi @eileenmcnaughton 

Didn't catch this as you committed / commented ~20 minutes after we'd shut down and gone home for the year – but the fix doesn't work.
I can see it added the table alias in the resulting SQL, but the problem is that it's not specifying the contact table in the LHS of the condition.  From some further investigation it seems that it's not setting either `$this->_aliases[$this->_tagFilterTable]` or `$this->_aliases[$civicrm_tag]` which are required for `CRM_Report_Form->tagWhereClause(...)`

**Comment by eileenmcnaughton** [comment]
@agileware-fj I think https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/179 will fix this
