### ISSUE TITLE
Actions.tpl override is not necessary

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.extendedreport#19]
Hi Eileen - I assume the same applies here as https://github.com/eileenmcnaughton/nz.co.fuzion.reportbase/issues/4 ?

**Comment by jmcclelland** [comment]
Just created: https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/20

**Comment by eileenmcnaughton** [comment]
This is removed. Note the override allowed flexibility (sometimes) as which contact the 'add to group' function applied to & that is gone at the moment (e.g add employer rather than the person you searched on)
