### ISSUE TITLE
Can't create new report from "Extended Report - Activity Pivot Chart (CiviCase)"

### ISSUE THREAD

**Issue by mikantchap** [eileenmcnaughton/nz.co.fuzion.extendedreport#217]
Hi 

We have an issue with report creation - is it a bug in the extension?

thanks Mike

*******************************************************************************

Go to Create New Report from Template = civicrm/report/template/list?reset=1&compid=7
Click on Extended Report - Activity Pivot Chart (CiviCase) = civicrm/report/case/activity/pivot?reset=1

The selects / fields on the Pivot table tab are briefly visible before disappearing.
A warning is shown:

Warning: Declaration of CRM_Extendedreport_Form_Report_ExtendedReport::generateFilterClause($field, $fieldName, $tableName) should be compatible with CRM_Report_Form::generateFilterClause($field, $fieldName) in require_once() (line 7 of /home/XXXXXXX/public_html/sites/default/files/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

Using version 3.5 of the extension with CiviCRM 5.8.2

**Comment by eileenmcnaughton** [comment]
It's likely that the function was moved into core but slight amended causing an incompatibility. I have a lot of fixes in this extension but they are all in the unreleased 4.0 version - however you can download it directly from github

**Comment by mikantchap** [comment]
Hi Are you able to say when the next release might be?

**Comment by eileenmcnaughton** [comment]
@mikantchap I put it out - I was kinda hanging off for more testing but since there seems to be a bug in 3.5 I figure it's better to put it out

**Comment by mikantchap** [comment]
Hi @eileenmcnaughton does this release specifically address the reported issue above?

**Comment by eileenmcnaughton** [comment]
@mikantchap I'm not sure but if it still exists I'll fix it in 4.x

**Comment by Sez0105** [comment]
@eileenmcnaughton 

The upgrade to version 4 hasn't resolved the issue, getting a syntax error (this is on a pivot extended report) 

On a activity extended report- can't select any information in the 'column' It isn't loading the page correctly.

Using CiviCRM 5.10.4

**Comment by eileenmcnaughton** [comment]
I've re-opened this

**Comment by eileenmcnaughton** [comment]
OK - I'm pretty sure it's fixed now - I'm gonna put out 4.1 soon which should work
