### ISSUE TITLE
Transaction Date in Extended Reports

### ISSUE THREAD

**Issue by mwestergaard** [eileenmcnaughton/nz.co.fuzion.extendedreport#219]
@eileenmcnaughton I applied the same fix you did for https://github.com/civicrm/civicrm-core/pull/13571 to correct the issue with time values missing in Transaction Date. It seems to work, but I have only tested with your "Extended Report - Bookkeeping with extra fields".

> *** ExtendedReport.php	2019-02-17 14:37:34.068854775 -0700
> --- ExtendedReport.php-	2018-05-07 12:33:52.052419993 -0700
> ***************
> *** 4206,4212 ****
>           'trxn_date' => array(
>             'title' => ts('Transaction Date'),
>             'default' => TRUE,
> !           'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
>             'operatorType' => CRM_Report_Form::OP_DATE,
>             'is_fields' => TRUE,
>             'is_filters' => TRUE,
> --- 4206,4212 ----
>           'trxn_date' => array(
>             'title' => ts('Transaction Date'),
>             'default' => TRUE,
> !           'type' => CRM_Utils_Type::T_DATE,
>             'operatorType' => CRM_Report_Form::OP_DATE,
>             'is_fields' => TRUE,
>             'is_filters' => TRUE,

**Comment by mwestergaard** [comment]
Apologies. I was still looking at v3.5. 

*** ExtendedReport.php	2019-02-17 20:27:37.663021008 -0700
--- ExtendedReport.php-	2019-01-29 13:28:15.000000000 -0700
***************
*** 3725,3732 ****
          'trxn_date' => array(
            'title' => ts('Transaction Date'),
            'default' => TRUE,
!           'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
!           'operatorType' => CRM_Report_Form::OP_DATETIME,
            'is_fields' => TRUE,
            'is_filters' => TRUE,
          ),
--- 3725,3732 ----
          'trxn_date' => array(
            'title' => ts('Transaction Date'),
            'default' => TRUE,
!           'type' => CRM_Utils_Type::T_DATE,
!           'operatorType' => CRM_Report_Form::OP_DATE,
            'is_fields' => TRUE,
            'is_filters' => TRUE,
          ),

**Comment by eileenmcnaughton** [comment]
OK thanks - I fixed it
