### ISSUE TITLE
4.6 readyness

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.extendedreport#23]
With the 4.6 in beta since today i was wondering, do you foresee any issues with compatibility (or would you think this extension will have no big issues working in 4.6? Of course I will also try and test myself, but you know the architecture of the extension and changes in civicrm better than I do :-)

**Comment by eileenmcnaughton** [comment]
the main issue is that there are overrides to the criteria.tpl - which changes in 4.6 - I'm trying to improve on the 4.6 version but I haven't figured out yet how to make the extension support 4.6 AND 4.4

**Comment by eileenmcnaughton** [comment]
I've ported all the 4.6 tpl stuff - seems Ok on 4.6 - pending any issues.
