### ISSUE TITLE
Address History Report doesn't handle separate log database

### ISSUE THREAD

**Issue by pfigel** [eileenmcnaughton/nz.co.fuzion.extendedreport#247]
In Civi environments where the log tables are stored in a separate database (via `CIVICRM_LOGGING_DSN`), the Address History Report causes a DB error because the generated SQL assumes the log tables are in the same database as the rest of Civi.

The report should check and parse `CIVICRM_LOGGING_DSN` and fully qualify the table with the obtained database name.

**Comment by pfigel** [comment]
I have a preliminary fix [here](https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/compare/master...greenpeace-cee:fix-addresshistory-db) that works for our specific use-case (description in the commit message), but breaks `Contact_AddressHistoryTest` and probably other ways one might use this report. Hopefully I can double back to this fix in the future, but if someone wants to pick this up (or is in need of a workaround), it might help.

**Comment by eileenmcnaughton** [comment]
Another gap on this report is that we are using a wmf mechanism to find contacts merged into the given contact. This is something we looked to upstream but instead wound up with an api upstream

Contact.getmergedto 

which this report should be updated to use
