### ISSUE TITLE
Contact_honor_id in DetailExtended.php and ParticipantExtended.php

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.extendedreport#25]
With civicrm 4.5 I believe the honor field was dropped from the contribution table.
It seems two reports still try to use it causing a fatal error for us (on 4.6)
[nativecode=1054 ** Unknown column 'contribution_civireport.honor_contact_id' in 'on clause']

I know officially this extension supports civicrm until 4.4 so I would understand if they are no priority to fix for 4.5/4.6. But if these would only be small compatibility fixes they would be nice :-)

DetailExtended.php line 466:
    // include Honor name field
    if ($this->_nameFieldHonor) {
      $this->_from .= "
            LEFT JOIN civicrm_contact contacthonor
                      ON contacthonor.id = {$this->_aliases['civicrm_contribution']}.honor_contact_id";
    }

**Comment by eileenmcnaughton** [comment]
Can you see if this is OK on master branch now?

**Comment by eileenmcnaughton** [comment]
I'm going to close this on the assumption its fixed since there is a commit against & no evidence it failed
