### ISSUE TITLE
Adding Notes to Bookkeeping with Extra Fields report

### ISSUE THREAD

**Issue by mwestergaard** [eileenmcnaughton/nz.co.fuzion.extendedreport#262]
I use the Bookkeeping with Extra Fields report extensively, except for one case where I need the Contribution Notes alongside the transactions. I lifted the code for Notes from DetailExtended.php and dropped it in BookkeepingExtended.php. It seems to work, but I don't know if I've introduced any issues. Here's the diff.

```
87c87,88
<     ));
---
>     ))
>     + $this->getColumns('Note');
182a184,190
>     }
>     // include contribution note
>     if ($this->isTableSelected('civicrm_note')) {
>       $this->_from .= "
>             LEFT JOIN civicrm_note {$this->_aliases['civicrm_note']}
>                       ON ( {$this->_aliases['civicrm_note']}.entity_table = 'civicrm_contribution' AND
>                            {$this->_aliases['civicrm_contribution']}.id = {$this->_aliases['civicrm_note']}.entity_id )";
```

**Comment by eileenmcnaughton** [comment]
So this would cause inaccurate results if there is more than one note for a given contribution. I think the data model supports that but not the UI

**Comment by mwestergaard** [comment]
Ok, thanks. I hadn't considered that. Would that also be true of the existing "Contributions Detail with extra fields" report, if the UI ever supported additional notes?

**Comment by eileenmcnaughton** [comment]
yes it would

**Comment by andyburnsco** [comment]
How can there be more than one note for a given contribution? I don't follow, sorry.
