### ISSUE TITLE
Extended activity report- not saving source contact filter

### ISSUE THREAD

**Issue by alarmingcod** [eileenmcnaughton/nz.co.fuzion.extendedreport#263]
I've created an extended activity report (Extended Report - Activities, includes multi-contact custom fields)

Field choice works great, but when I try and add a filter source contact id is equal to xxxx, and preview the report is fine, if I try and save settings,  the filter is not saved and reverts to id is equal to or less than xxxx.

I can work with what I've got. And export results after preview. Would be nice to be able to create a series of results for different source contacts

**Comment by alarmingcod** [comment]
Using Drupal 7.66 civi 5.10.4

**Comment by alarmingcod** [comment]
Hi again!

Source name filter saves fine.  This is a really minor quibble.

**Comment by eileenmcnaughton** [comment]
out of interest does source_contact_id work in the url? I think the syntax is like source_contact_id_op=in&source_contact_id_value=5
