### ISSUE TITLE
Custom fields not showing on Memberships Filter tab

### ISSUE THREAD

**Issue by avall-llovera** [eileenmcnaughton/nz.co.fuzion.extendedreport#267]
We are currently using Civicrm 5.13.4. & Extended Reports 4.4

We have been using the extension for a while, but since version 4.2 custom fields in membership reports in the filter column disappeared.

**BEFORE**
![image](https://user-images.githubusercontent.com/48087290/58874332-cfd5fe80-86c8-11e9-871b-271dd93ddbbf.png)

**AFTER**
![image](https://user-images.githubusercontent.com/48087290/58874366-ef6d2700-86c8-11e9-9059-3ca058c19115.png)

**Comment by eileenmcnaughton** [comment]
Hi, this should fix it https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/268

**Comment by avall-llovera** [comment]
Thank you! It works perfectly.
