### ISSUE TITLE
Event age column has disappeared

### ISSUE THREAD

**Issue by avall-llovera** [eileenmcnaughton/nz.co.fuzion.extendedreport#269]
Back in 3.5, in the "Extended Report - Participants" report, there was a column which showed the age of a participant that she/he had in the specific event.

Is it possible to recover that column?

**Comment by avall-llovera** [comment]
We intend to regain that functionality that was useful to us. This is still happening in CiviCRM v.5.28, Extended Report v.5.4

**Comment by eileenmcnaughton** [comment]
Ok - here ya go https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/commit/74d117be32103b446b4c5306a171149e7332d18e
