### ISSUE TITLE
4.6 not supporting custom data from multiple contacts

### ISSUE THREAD

**Issue by eileenmcnaughton** [eileenmcnaughton/nz.co.fuzion.extendedreport#27]
e.g the extended activity report used Select 2 to offer a selection of custom fields for assignee, target, or source. 

Select 2 is no longer in core. Unfortunately the reason I chose to use Select 2 is that it allowed the fields to be re-ordered - & the columns were re-ordered based on that. The new widget doesn't seem to allow that

**Comment by francescbassas** [comment]
Same for extended relationship report. After 4.6 upgrade our reports can't show custom fields.

**Comment by francescbassas** [comment]
Not sure if the previous comment is related to this issue. @eileenmcnaughton can you confirm that missing custom fields columns at extended relationship report is due to this issue? Otherwise I would open another issue.

**Comment by francescbassas** [comment]
Hi, Eileen.

Since the update we can not extract data from multiple contacts on our Relationship Extended reports. How should approach solving this problem? The solution is simple or complicated?

**Comment by eileenmcnaughton** [comment]
I re-added the ability to select these fields - although I haven't been able to restore the ability to sort the fields at this stage.

**Comment by francescbassas** [comment]
Great Eileen! Works fine again! Thanks so much.
