### ISSUE TITLE
"Grouping" custom fields do not appear after upgrading to 4.4

### ISSUE THREAD

**Issue by projects-douglassdigital** [eileenmcnaughton/nz.co.fuzion.extendedreport#270]
Hello,
I have upgraded "ExtendedReport" (nz.co.fuzion.extendedreport) civicrm extension to 4.4 and the "Grouping" custom fields no longer appear (see the screenshot). Is there something I need to do? (they were appearing on version 3.5)
![Untitled](https://user-images.githubusercontent.com/21055733/59137864-b7dcd400-8981-11e9-91e3-afc7da68653f.png)

**Comment by francescbassas** [comment]
This week the 4.5 version has been released with some changes related with custom fields on pivot reports https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/commit/4b1fcc6ffb9d5b3697ab491956d573bee6a24ea2.

I suspect that your problem is not solved with this changes but you can confirm it upgrading the extension to 4.5?

**Comment by eileenmcnaughton** [comment]
Can you please specify which report this is on?

**Comment by projects-douglassdigital** [comment]
4.5 version makes no difference.
it is the "Extended Report - Event Overview" (Extended Report - Statistics across events)

![image](https://user-images.githubusercontent.com/21055733/59163005-9c450b00-8af2-11e9-83a2-45c278533dc8.png)

**Comment by eileenmcnaughton** [comment]
I just pushed up a fix - are you able to test it before I cut a release tag?

**Comment by projects-douglassdigital** [comment]
hi,
the custom fields appear now, however in version 3.5 there was also "Quantity" field against each custom field (i.e. Event Industries - Event Industries Quantity, see the screenshot). Can this also be done?
Also I'm getting few php notices - :  Undefined index:  in /wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php
:  Undefined index: event_id in /wp-content/uploads/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php

![image](https://user-images.githubusercontent.com/21055733/59357129-2a530880-8d22-11e9-9312-100e6b6f03b8.png)

**Comment by eileenmcnaughton** [comment]
I'm a little confused how those quantity fields worked - can you explain what your reports achieved with them?

**Comment by stoycho-douglassdigital** [comment]
Hi,
if you select group by for quantity field (in the screenshot below "Event Industries Quantity" as an example) a "Quantity Selected" column is added at the end of the report result.
In the file nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php the quantity field is added on line 2272 on version 3.5
On version 4.6 in the same file it is on line 7437, however there is an extra condition - if ($curFields[$fieldName]['type'] === CRM_Utils_Type::T_INT) {  what is the reason for this condition?

![Untitled](https://user-images.githubusercontent.com/18311287/60812341-2aabbb80-a189-11e9-816c-c05bda9c555f.png)

**Comment by eileenmcnaughton** [comment]
I think this might give you back what you want - https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/285

**Comment by projects-douglassdigital** [comment]
Are you going to release a new tag or should I use the master branch to try it out?

**Comment by eileenmcnaughton** [comment]
@projects-douglassdigital you'll need to checkout the cols branch because it's not merged yet

**Comment by projects-douglassdigital** [comment]
Hi, sorry to keep bothering but this is still not working.
1) If I group by custom field - it is not appearing under Grouping(s).
2) If I use the filters with custom field with Contains - it is not returning result as it is not joining the tables properly. The "Event Funder" is an INT field in the custom DB table containing the contact_id and in the query it is used directly with the like - civicrm_value_events_custom_fields_8.event_funder_65 LIKE '%Greater Cambridge Partnership%'. In version 3.5 it was correctly Joining the `civicrm_contact` table and civicrm_contact.display_name was used in the LIKE '%Greater Cambridge Partnership%'.
See the screenshots.

![Untitled](https://user-images.githubusercontent.com/21055733/62089007-36a60d00-b25f-11e9-94a5-56a13fc25651.png)

![Untitled2](https://user-images.githubusercontent.com/21055733/62089012-3b6ac100-b25f-11e9-9fe2-23fb2e141c1f.png)


--



--

**Comment by eileenmcnaughton** [comment]
Ok - these should be fixed in 4.7 - tagged against CiviCRM 5.16
