### ISSUE TITLE
Hide columns with zero count doesn't work correctly on 4.5

### ISSUE THREAD

**Issue by avall-llovera** [eileenmcnaughton/nz.co.fuzion.extendedreport#271]
On Event Pivot chart it didn't hide the columns correctly.

**BEFORE**
![Hide 0 columns off](https://user-images.githubusercontent.com/48087290/59261351-9445b200-8c3d-11e9-8409-ebba18c9d9f1.png)
We can see that there are 18 columns where 11 of them are 0.

**AFTER**
![Hide 0 columns on](https://user-images.githubusercontent.com/48087290/59261369-9ad42980-8c3d-11e9-929b-6f54e0ae2dcf.png)
When we select the option hide columns with zero count it shows 6 columns when originally where 7 of them!

It's highly probable that this behaviour can be replicated in other reports.
Any idea why this is happening?

Thanks!

**Comment by eileenmcnaughton** [comment]
@avall-llovera your issue report makes ut look like you have a patch for this but I can't see it - is there one or is this just a fix request

**Comment by avall-llovera** [comment]
Sorry, it is a fix request. I edited the Issue to be more detailed and self-explanatory

**Comment by eileenmcnaughton** [comment]
I just tried & couldn't replicate this - but I think it might have been fixed in between, just that I didn't publish a release. Anyway I just released 4.6 (works on civi 5.15) so maybe check if the bug is still there?

**Comment by francescbassas** [comment]
Currently it only shows the columns that had values in the first row of the report. I have proposed a PR to fix it https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/288.

**Comment by eileenmcnaughton** [comment]
Closing as I merged #288
