### ISSUE TITLE
Extended Report - Flexible contact report - Filter by Group not working.

### ISSUE THREAD

**Issue by danfish** [eileenmcnaughton/nz.co.fuzion.extendedreport#274]
Created a  Flexible contact report from template - filter by Group does not appear to work - returns all contact records.  Using master branch from today 6/12/19.  

CiviCRM 5.14 on Drupal 7.67
Thanks.

**Comment by eileenmcnaughton** [comment]
fixed https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/281

**Comment by danfish** [comment]
Thank you!
