### ISSUE TITLE
SQL_CALC_FOUND_ROWS deprecated as of MySQL 8.0.17

### ISSUE THREAD

**Issue by JoeMurray** [eileenmcnaughton/nz.co.fuzion.extendedreport#275]
https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows indicates 'The SQL_CALC_FOUND_ROWS query modifier and accompanying FOUND_ROWS() function are deprecated as of MySQL 8.0.17 and will be removed in a future MySQL version.'

This is used in this extension:
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Contribute/DetailExtended.php:      $select = str_ireplace('SELECT SQL_CALC_FOUND_ROWS ', 'SELECT ', $this->_select);

./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Pledge/Sybuns.php:      $getContacts = "SELECT SQL_CALC_FOUND_ROWS {$this->_aliases['civicrm_contact']}.id as cid {$this->_from} {$this->_where} GROUP BY {$this->_aliases['civicrm_contact']}.id {$this->_limit}";
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Pledge/Lybuns.php:      $getContacts = "SELECT SQL_CALC_FOUND_ROWS {$this->_aliases['civicrm_contact']}.id as cid {$this->_from} {$this->_where}  GROUP BY {$this->_aliases['civicrm_contact']}.id {$this->_limit}";
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Pledge/Btbns.php:      $getContacts = "SELECT SQL_CALC_FOUND_ROWS {$this->_aliases['civicrm_contact']}.id as cid {$this->_from} {$this->_where}  GROUP BY {$this->_aliases['civicrm_contact']}.id {$this->_limit}";
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Pledge/Sybunt.php:      $getContacts = "SELECT SQL_CALC_FOUND_ROWS {$this->_aliases['civicrm_contact']}.id as cid {$this->_from} {$this->_where} GROUP BY {$this->_aliases['civicrm_contact']}.id {$this->_limit}";
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/Pledge/Lybunt.php:      $getContacts = "SELECT SQL_CALC_FOUND_ROWS {$this->_aliases['civicrm_contact']}.id as cid {$this->_from} {$this->_where}  GROUP BY {$this->_aliases['civicrm_contact']}.id {$this->_limit}";
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php:      $select = str_ireplace('SELECT SQL_CALC_FOUND_ROWS ', 'SELECT ', $this->_select);
./civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php:      //    $select = str_ireplace('SELECT SQL_CALC_FOUND_ROWS ', $select, $this->_select);

**Comment by eileenmcnaughton** [comment]
ok ripped em out
