### ISSUE TITLE
Certain fields are exporting as option values instead of labels

### ISSUE THREAD

**Issue by guyiac** [eileenmcnaughton/nz.co.fuzion.extendedreport#278]
Running version 4.5. 

Activity Type, Activity Status, and a number of custom fields we are using are exporting as option values (numbers) instead of labels (words).

**Comment by eileenmcnaughton** [comment]
@guyiac I just tried this on 'Extended Report - activities' and didn't replicate it 

I tried on master branch - but I think the difference is not in the code but in something you are doing differently...

<img width="992" alt="Screen Shot 2019-07-05 at 2 12 25 PM" src="https://user-images.githubusercontent.com/336308/60693602-02288500-9f2f-11e9-973f-d545cc5698d0.png">

**Comment by guyiac** [comment]
Ok, thanks so much for taking a look and letting me know! I’ll let you know what I find.

**Comment by eileenmcnaughton** [comment]
@guyiac I should also point out that it's worth mentioning when you log tickets if the requirement is for an organisation that is a member of CiviCRM because I prioritise those

**Comment by guyiac** [comment]
Ok, good to know. Do Partners count? This was for Greenleaf’s Civi - I actually use our software as my own CRM. :-)

**Comment by eileenmcnaughton** [comment]
Well no, when I prioritise members it's because I want to encourage organisations that use Civi to subscribe as members - so to get my unofficial member prioritisation you would need to sign your own site up as a member
