### ISSUE TITLE
Custom Field Display tab is missing in Flexible contact report in latest version

### ISSUE THREAD

**Issue by yashodha** [eileenmcnaughton/nz.co.fuzion.extendedreport#287]
In earlier version, we had a separate tab for having custom fields as columns
![extended_custom](https://user-images.githubusercontent.com/3455173/62056952-46602a00-b23c-11e9-8b54-91827706ae98.png)

Now in the latest code, we don't have a way to select the custom fields as columns

![extended_without_custom](https://user-images.githubusercontent.com/3455173/62056994-5b3cbd80-b23c-11e9-8647-9dc483f0c538.png)

It looks like a regression.

**Comment by eileenmcnaughton** [comment]
ok - try #289
