### ISSUE TITLE
Event pivot chart report shows incorrect participant role count

### ISSUE THREAD

**Issue by agileware-pengyi** [eileenmcnaughton/nz.co.fuzion.extendedreport#297]
When a participant has more than one role, the report shows an incorrect count for each role.

Step to reproduce

1. Create an event and add a participant with multiple roles
2. Create a new report from Event Pivot Chart template
3. Set the `Select Column Header` to `Participant Role`
4. View the result

![event_pivot_chart](https://user-images.githubusercontent.com/49378827/62744948-46f28f00-ba8c-11e9-83ac-47446c6a5806.png)

Agileware ref: CIVICRM-1288

**Comment by eileenmcnaughton** [comment]
dang - I wonder if it is the same as https://github.com/civicrm/civicrm-core/pull/14982

**Comment by agileware-pengyi** [comment]
> dang - I wonder if it is the same as [civicrm/civicrm-core#14982](https://github.com/civicrm/civicrm-core/pull/14982)

Not sure. I haven't go to the code yet.

**Comment by agileware-pengyi** [comment]
Realy a core issue? https://lab.civicrm.org/dev/core/issues/76

**Comment by eileenmcnaughton** [comment]
@agileware-pengyi I think it's a bit tricky to solve - hence I backed out when I looked...
