### ISSUE TITLE
Adding county field to row field dropdown

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#299]
How can we modify the **Extended Report - Pivot data membership report** to include county in the row fields drop down?
![image](https://user-images.githubusercontent.com/18341942/63707084-aecc0800-c7f6-11e9-89d9-8727c5a1849a.png)

What report is this based off of?

**Comment by eileenmcnaughton** [comment]
Looks like it's just a case of joining in the address table https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/300

**Comment by andyburnsco** [comment]
Tested #299 patch and for instance in PA, USA it returns 103 counties (there is only 67 counties in PA) and when I click next on the pager, it still shows the same counties.

Records 1-50
![image](https://user-images.githubusercontent.com/18341942/64228298-fa904880-ceab-11e9-809a-b16b4222921d.png)

Records 51-100.

![image](https://user-images.githubusercontent.com/18341942/64228346-23b0d900-ceac-11e9-8bbd-bb07887957da.png)
