### ISSUE TITLE
Ordinality and Line Items

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#30]
Eileen, is there anything in extended reports (2.0) that would allow us to search line item financial types AND filter on Ordinality ("first donation")?

**Comment by eileenmcnaughton** [comment]
There isn't at the moment. I think that would be patch-welcome for the CRM_Extendedreport_Form_Report_Price_Lineitem (with a unit test) - but given this is over 2 years old I'm going to close it out
