### ISSUE TITLE
Pledge SYBUNT / LYBUNT Reports not working?

### ISSUE THREAD

**Issue by guyiac** [eileenmcnaughton/nz.co.fuzion.extendedreport#303]
Is anyone else having an issue getting these reports to render? I get the search portion, and then the section showing what criteria were applied, but then nothing shows up under the results.

**Comment by eileenmcnaughton** [comment]
fixed?

**Comment by guyiac** [comment]
Sorry, yes, just tested, everything seems to be working. I apologize for not getting back to you!
