### ISSUE TITLE
Yes/No Responses being shown and exported all as No

### ISSUE THREAD

**Issue by Barijohn** [eileenmcnaughton/nz.co.fuzion.extendedreport#316]
Hi, 

Currently have a problem when running an activity report with Yes/No Radio buttom custom data, the only options being shown are No no matter what is selected and this is also what is being exported. Can see the original data in the activity and that is correct. 

The site is running CiviCRM 5.13.4 and extended reports 4.8. Rebuilt the report but still got the same problem. 

I can replicate this on DMaster Demo CiviCRM version 5.20.alpha1. Set-up some custom Yes/No data in an activity. Installed Custom Reports and created an activity report. Just shows No.

**Comment by eileenmcnaughton** [comment]
Thanks for confirming that master is also affected - I've fixed this & dropped a new release with the fix (against 5.18)

**Comment by Barijohn** [comment]
Excellent! Worked perfectly, site is still on 5.13.4 so works on that as well as latest DMaster Demo. 

Thanks for fixing it so quickly :)
