### ISSUE TITLE
Making a field be required but conditionally visible

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/nz.co.fuzion.extendedreport#327]
I'm doing some cleanup on broken `alterDisplay()` methods, and I noticed there seems to be a feature in core that I can't replicate in Extended Report.

1. On the *Columns* tab, *Contact ID* is listed.
1. If you check the *Contact ID* box, it appears on the report.
1. If you leave the *Contact ID* box unchecked, it does NOT appear on the report, but is still in the SQL query (and `$row` array), so it can be used in `alterDisplay()`.

In Extended Report, I can't see that there's a way to specify that `required = TRUE` but `no_display` is conditional on whether the field is selected.  There's also inconsistency (in core) of what `required`  means, and is contingent on `no_display` (but probably not on purpose).

What do you think of the idea of an option that lets you set a field as described above?  The use case is a field that can be selected normally to appear or not in results, but will always be available for use in `alterDisplay()`.  I can code it if I can think of what the name should be :)

**Comment by eileenmcnaughton** [comment]
I feel like I tried to go down the path of having a 'depends' or something so that one var could indicate another as being included if that one is. The issue with 'always in' is that if it's not the base table it can trigger a join I think.

**Comment by MegaphoneJon** [comment]
Ah, I saw something of that nature.  I think this is as far as my client will go, but it's good to keep in mind for the future.
