### ISSUE TITLE
Total Paid and Balance as fields and filters? 

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.extendedreport#33]
Since partial payments were introduced in civicrm 4.5 are there plans for the extendedreport extension to include the "total paid" and "balance" as fields and filters?

I also put this on SE to see if we can adjust the core reports to accomodate this.
http://civicrm.stackexchange.com/questions/3349/contribution-report-with-total-paid-and-balance-fields

**Comment by eileenmcnaughton** [comment]
no plans at the moment (ie. none of our customers have asked for it & this extension is primarily done to customer funding)

**Comment by eileenmcnaughton** [comment]
I'm going to close this out for now since there is no funding / momentum on it

**Comment by magnolia61** [comment]
If you would feel the momentum has changed... :-)
I think partial payments in CivICRM are becoming more common and the support for it as well.
Just a ping to see if other people would also be interested...

**Comment by eileenmcnaughton** [comment]
hmm I'll re-open for profile

**Comment by magnolia61** [comment]
:-) As support for partial payments and proper recording of financial transactions is rapidly maturing (thank you Eileen), I would again like to thumbs up this idea :-) If I can help or if you have guidance for me to attribute, I'd be glad to!
