### ISSUE TITLE
"Hide columns with zero count" on pivot table reports has faulty logic

### ISSUE THREAD

**Issue by lcdservices** [eileenmcnaughton/nz.co.fuzion.extendedreport#341]
The option to "Hide columns with zero count" is intended to let you essentially extend the filters used for the report to the display. However, the current logic is flawed. Currently it recurses through only the first row of results and if a value in a given column is 0, it suppresses the column. A more meaningful and useful behavior is to recurse through the grand total row and hide columns with a 0 value. That is more reflective of the expected behavior.

**Comment by lcdservices** [comment]
ok... nevermind. went to prepare a PR and realized that this is already fixed in the master branch. just hasn't been released yet.

**Comment by francescbassas** [comment]
I think 4.9 and 5.0 they should have this behavior fixed

See https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/271#issuecomment-517632969
