### ISSUE TITLE
Tags do not filter properly in CRM_Extendedreport_Form_Report_RelationshipExtended

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#351]
Two issues related to tags:

1. If you setup a tag and try to filter on it, it does not have any effect. 
2. If you set up a tag set and try to select a tag from that tag set, it does not show in the tag filter.

I have tested if making the tag reserved or not reserved makes a difference. It does not.

I successfully used a group for a filter instead. However, we would prefer to use a tag.

**Comment by agileware-justin** [comment]
Thanks for reporting @andyburnsco - can confirm this bug #metoo

Agileware Ref: CIVICRM-1447

**Comment by eileenmcnaughton** [comment]
If you want to submit a patch please make sure you do a test - I've just lost some time writing tests for patches I accepted without tests & want  to avoid too much more of that

**Comment by agileware-justin** [comment]
For those looking for a solution, as a workaround recommend setting up a similar Report using the Data Processor extension, https://lab.civicrm.org/extensions/dataprocessor

**Comment by eileenmcnaughton** [comment]
It looks like this was addressed in https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/421 - although as with the group filter it works on contact a
