### ISSUE TITLE
Relationship Extended report fails whith relationship type filter

### ISSUE THREAD

**Issue by francescbassas** [eileenmcnaughton/nz.co.fuzion.extendedreport#36]
We don't know exactly what is the origin of this problem but we come from a 4.5 CiviCRM with 1.8 Extended Report extension and we upgrade to 4.6.5 CiviCRM with 2.0 Extended Report.

We've noticed that since this change we no longer generate more Relationship Extended reports filtering by relationship type.

We get this error message

    Unknown column '1_a_b' in 'where clause'

This is the affected part of the query:

    WHERE ( participant.status_id IN (1) ) AND ( relationship.relationship_type_id IN (1_a_b) )

**Comment by eileenmcnaughton** [comment]
Does your PR mean this can be closed now?

**Comment by francescbassas** [comment]
For me yes! Thanks
