### ISSUE TITLE
Extended Report requires "CiviCRM: view all contacts" Permission?

### ISSUE THREAD

**Issue by clement8888** [eileenmcnaughton/nz.co.fuzion.extendedreport#360]
CiviCRM5.10.4 ExtendedReport V4. WordPress 5.0.8

Hello, i was generating a report from ExtendedReport from an account that has a restricted view on the records in CiviCRM which was done by the following:

1. Didn't give permission to "CiviCRM: view all contacts" to the role
2. Created a ACL Role "ABC"
3. Assigned the ACL Role ABC to a Group "EFG" containing user contacts
4. Edit ACL to give Role ABC to have EDIT operation over another Group "HIJ" of contacts

this worked out for me to restrict those users grouped under ABC to only see/edit contacts in assigned to group HIJ.

However, when I generate a Relationship report using the ExtendedReport, there is a DB error reported when the Preview button is clicked.  There doesn't seem to be a problem when other forms of ExtendedReport (say Activities) is generated.  However, when I allow the permission to "CiviCRM: view all contacts" to the said role, the Relationship report will be generated OK, though with too many contacts beyond what was supposedly allowed to access by this role.

Any advice is appreciated.  Thanks!

**Comment by eileenmcnaughton** [comment]
This seems to be fixed in the master branch now (which I will release as 5.4 against 5.28
