### ISSUE TITLE
Feature Request: Include contribution note column

### ISSUE THREAD

**Issue by tapashdatta** [eileenmcnaughton/nz.co.fuzion.extendedreport#365]
I have used this extension for first time today and while exploring the price set field report, I have found out that I could not include the “contribution note” column. It was an important part of my report to include that field. So my request would be, please include it if possible on a future release. Thanks

**Comment by mwestergaard** [comment]
@tapashdatta See similar discussion in https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/262. I suspect the issue raised there about the possibility of multiple notes would apply here, as well. I am using the "fix" I suggested, but with the understanding that it could break.

**Comment by tapashdatta** [comment]
@mwestergaard Thanks! But looking at the availability of "Contribution Note" field it appears only 1 contribution note be applicable per transaction. Or am I missing something?

**Comment by mwestergaard** [comment]
@tapashdatta Yes, I believe that's what Eileen described. The current UI supports only one note per transaction, but the data model could allow for multiple notes in the future.

**Comment by tapashdatta** [comment]
@mwestergaard Thanks for clarifying.
