### ISSUE TITLE
Date locationisation and datePicker

### ISSUE THREAD

**Issue by chriscant** [eileenmcnaughton/nz.co.fuzion.extendedreport#378]
Hello.  For a UK based site, the Extended Report - Contributions Detail with extra fields - Template doesn't use UK date formatting and doesn't provide a datePicker. It would be nice if this were able to be fixed, thanks very much.
![image](https://user-images.githubusercontent.com/1153272/84758041-d75b0380-afbc-11ea-9d74-e61a0580245c.png)

**Comment by eileenmcnaughton** [comment]
This commit in master https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/commit/29ce1cd83f5ccb226fa2ed044d7df866733a22d3 should have done that

**Comment by chriscant** [comment]
OK, great. Should have spotted that. Will try to give it a whirl soon.

**Comment by chriscant** [comment]
That seems to work fine thanks on a test site.
I see there's extra time fields in there too :-)
Is there any reason why I shouldn't make this live?
Thanks, Chris

**Comment by eileenmcnaughton** [comment]
I just tagged 5.2 as a release - so you can go live with what you have - or the tagged release

**Comment by chriscant** [comment]
That's brilliant thanks.
