### ISSUE TITLE
Extended Reports Participants  - in Events - Phone field error

### ISSUE THREAD

**Issue by chrisdubrow** [eileenmcnaughton/nz.co.fuzion.extendedreport#38]
Hey there

Suddenly discovered an issue with my extended Event reports.. 
Tested on two systems: 
Wordpress 4.3 CiviCRM 4.6.8
also an issue for my local set up running
Wordpress 4.3 Civicrm 4.6.4

I Create a new report using "Extended Report - Participants" template. 
If I select 'Phone' field under Columns tab
And try to preview report - i get error - 
" Sorry but we are not able to provide this at the moment.
DB Error: no such field
Return to home page." 

Phone field works fine in non-extended report templates such as 
"Event Participant Report"
any ideas? 
Chris

**Comment by eileenmcnaughton** [comment]
Chris - I can take a look - but can you confirm you are using the latest version (ie. from github) of extended reports because there might be new fixes in there

**Comment by chrisdubrow** [comment]
Thanks for the response Eileen
It appeared to be the latest version 
- but we will upload the latest and test

**Comment by chrisdubrow** [comment]
Eileen  - have reloaded very latest version of extension from github master
and still get the error

**Comment by chrisdubrow** [comment]
HAng on !

**Comment by chrisdubrow** [comment]
Sorry - thought for a sec I was testing on wrong version - but alas - the fault stands..

**Comment by chrisdubrow** [comment]
Eileen - If you need coin for this do get back to me..

**Comment by eileenmcnaughton** [comment]
I finally got to this - it was pretty simple actually - I'm going to close as I'm pretty sure the patch I added does resolve it.

**Comment by chrisdubrow** [comment]
For Eileen
https://www.youtube.com/watch?v=e3mLoFndR6M

*Chris Dubrow*
0416 385 803
chris.dubrow@gmail.com

**Comment by eileenmcnaughton** [comment]
:-)
