### ISSUE TITLE
Add employer and job title fields

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#380]
This is a feature request to add employer and job title fields. I am specifically looking at _CRM_Extendedreport_Form_Report_Contribute_BookkeepingExtended_.

**Comment by eileenmcnaughton** [comment]
@andyburnsco I just added the job title https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/381 but the employer is actually already shown in the 'Organization Name' field - ie  you can see in the image that 2 rows have organization_name. In the first row it's an individual and the value in the field is the employer

<img width="851" alt="Screen Shot 2020-06-27 at 5 46 00 PM" src="https://user-images.githubusercontent.com/336308/85915735-15e69d00-b89e-11ea-9c4c-ec17c2d5b255.png">

**Comment by andyburnsco** [comment]
Ok. I see I was on Civi 5.24 which is using version 5.1 Extended Reports. 5.2 includes organization name. Thank you!
