### ISSUE TITLE
Multiple errors after update from git clone

### ISSUE THREAD

**Issue by joemcl** [eileenmcnaughton/nz.co.fuzion.extendedreport#39]
Just updated from git clone and getting multiple errors - I first disabled in Civi, did rm -r from the command line, then git clone, then drush updatedb, then Cleared Caches in Civi and re-installed in Civi. 

Errors are:
Notice: Undefined offset: 0 in CRM_Extendedreport_Form_Report_ExtendedReport->aggregateSelect() (line 592 of /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).
Warning: Invalid argument supplied for foreach() in CRM_Extendedreport_Form_Report_ExtendedReport->aggregateSelect() (line 592 of /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).
Warning: htmlspecialchars() expects parameter 1 to be string, object given in krumo::_array() (line 1071 of /var/www/citizenactionny/my.citizenactionny.org/sites/all/modules/devel/krumo/class.krumo.php).
Warning: htmlspecialchars() expects parameter 1 to be string, object given in krumo::_array() (line 1071 of /var/www/citizenactionny/my.citizenactionny.org/sites/all/modules/devel/krumo/class.krumo.php).
Notice: Undefined index: metadata in CRM_Extendedreport_Form_Report_ExtendedReport->getFilterFieldValue() (line 758 of /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

And getting krumo errors - even with debugging and error handling turned off - 
... (Array, 2 elements)
Krumo version 0.2.1a | http://krumo.sourceforge.net Click to expand. Double-click to show path. Called from /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php, line 1753  
... (Array, 20 elements)
Krumo version 0.2.1a | http://krumo.sourceforge.net Click to expand. Double-click to show path. Called from /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php, line 1754

**Comment by joemcl** [comment]
So I'm only getting this error now - Notice: Undefined index: metadata in CRM_Extendedreport_Form_Report_ExtendedReport->getFilterFieldValue() (line 758 of /var/www/citizenactionny/my.citizenactionny.org/sites/default/civicrm/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php).

**Comment by joemcl** [comment]
So we're now on 4.6.11, and I'm going to update the extension from the latest build onto our staging site, then see if this issue is still occurring. Keeping my fingers crossed.

**Comment by eileenmcnaughton** [comment]
Joe - which report are you running?

**Comment by joemcl** [comment]
Hey Eileen sorry for the much-delayed reply. This appears often when refreshing my Dashboard on which I have 11 reports/dashlets. Not sure which one causes it.

**Comment by eileenmcnaughton** [comment]
I'm closing this as it is a bit dated & hard to resolve in it's current state. Note that I am discontinuing 4.6 support on this extension.
