### ISSUE TITLE
The ActivityExtended Report doesn't display any columns that are marked as being editable

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.extendedreport#40]
I'm running version with commit:

d69ed850530a30bc431f35b5b0830026cf571720

It seems that there is a confusion between whether to expect the activity id to be called civicrm_activity_id or civicrm_activity_activity_id.

**Comment by jmcclelland** [comment]
I'm not sure this is the right fix.. but it worked in my case.

**Comment by eileenmcnaughton** [comment]
yeah - I did kinda change the prefix along the way & it has had some fallout :-( I think the longest is the correct one now

**Comment by eileenmcnaughton** [comment]
closing - pretty sure your PR was the fix
