### ISSUE TITLE
Duplicate line item appearing in Extended Report

### ISSUE THREAD

**Issue by alexmarketaccess** [eileenmcnaughton/nz.co.fuzion.extendedreport#42]
One of our clients used civiCRM's New Membership feature to manually enter a new contribution that included a $25 membership, and a $25 donation:

![membership](https://cloud.githubusercontent.com/assets/15691820/11429863/9ffdfb18-944b-11e5-989c-0072e7af52b2.png)

We verified in the table civicrm_line_item that only two records existed for the contribution:

![lineitem](https://cloud.githubusercontent.com/assets/15691820/11429885/0896c498-944c-11e5-8bdc-6aec8e603618.png)

The Bookkeeping Transaction report shows the two line items correctly:

![bookkeeping](https://cloud.githubusercontent.com/assets/15691820/11429766/cbaa0d8e-944a-11e5-9683-ff3db96b7b3d.png)

But the Extended Report shows 3 line items:

![extendedreport](https://cloud.githubusercontent.com/assets/15691820/11429768/d811240e-944a-11e5-9459-d231cd046f3f.png)

The Extended Report query in the Developer panel is:
```
SELECT SQL_CALC_FOUND_ROWS civicrm_contact.display_name as civicrm_contact_civicrm_contact_display_name, sum(contribution.total_amount) as civicrm_contribution_contribution_total_amount_sum, line_item.financial_type_id as civicrm_line_item_line_item_financial_type_id, line_item.line_total as civicrm_line_item_line_item_line_total 

FROM civicrm_line_item line_item 
  LEFT JOIN civicrm_price_field_value price_field_value ON line_item.price_field_value_id = price_field_value.id 
  LEFT JOIN civicrm_price_field price_field ON line_item.price_field_id = price_field.id 
  LEFT JOIN civicrm_participant participant ON ( line_item.entity_id = participant.id AND line_item.entity_table = 'civicrm_participant') 
  LEFT JOIN civicrm_report_temp_line_items5138 as line_item_mapping ON line_item_mapping.lid = line_item.id 
  LEFT JOIN civicrm_contribution as contribution ON line_item_mapping.contid = contribution.id 
  LEFT JOIN civicrm_contact civicrm_contact ON contribution.contact_id = civicrm_contact.id 
  LEFT JOIN civicrm_event event ON (event.id = participant.event_id ) AND (event.is_template IS NULL OR event.is_template = 0) 

WHERE ( contribution.contribution_status_id IN (1) ) AND ( contribution.receive_date >= '20151126000000') AND ( contribution.receive_date <= '20151126235959' ) AND civicrm_contact.is_deleted = 0 

GROUP BY line_item.id WITH ROLLUP 

LIMIT 0, 50
```
Happy to provide any other assistance to help resolve this issue.

**Comment by eileenmcnaughton** [comment]
I've pushed a fix on this now
