### ISSUE TITLE
ExtendedReport extension throws fatal error on WordPress Access Control save settings

### ISSUE THREAD

**Issue by Firefly0101** [eileenmcnaughton/nz.co.fuzion.extendedreport#428]
With the extension enabled  the settings in WordPress Access Control cannot be saved.

Disabling this extension allows the settings to be saved.

The error displayed is "API error: is not of type String". This is displayed when enabling the extension or saving WordPress Access Control settings.

This is on Wordpress 5.5.1, with CiviCRM 5.28.1.

I've tried disabling other extensions and the issue only happens with Extended Report active. 

This is the trace:
`Exception: "API error: is not of type String"

#0 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(287): CRM_Core_ManagedEntities->onApiError("ReportTemplate", "create", (Array:8), (Array:3))
#1 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(173): CRM_Core_ManagedEntities->updateExistingEntity(Object(CRM_Core_DAO_Managed), (Array:4))
#2 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(146): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), (Array:34))
#3 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/ManagedEntities.php(127): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(398): CRM_Core_ManagedEntities->reconcile()
#5 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/ACL/Form/WordPress/Permissions.php(179): CRM_Core_Invoke::rebuildMenuAndCaches()
#6 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(504): CRM_ACL_Form_WordPress_Permissions->postProcess()
#7 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#8 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(45): CRM_Core_StateMachine->perform(Object(CRM_ACL_Form_WordPress_Permissions), "next", "Next")
#9 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_ACL_Form_WordPress_Permissions), "next")
#10 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_ACL_Form_WordPress_Permissions), "next")
#11 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(347): HTML_QuickForm_Page->handle("next")
#12 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Utils/Wrapper.php(98): CRM_Core_Controller->run()
#13 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(285): CRM_Utils_Wrapper->run("CRM_ACL_Form_WordPress_Permissions", "WordPress Access Control", (Array:0))
#14 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(68): CRM_Core_Invoke::runItem((Array:14))
#15 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:4))
#16 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-content/plugins/civicrm/civicrm.php(1601): CRM_Core_Invoke::invoke((Array:4))
#17 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-includes/class-wp-hook.php(287): CiviCRM_For_WordPress->invoke("")
#18 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters("", (Array:1))
#19 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-includes/plugin.php(478): WP_Hook->do_action((Array:1))
#20 /Users/cfrost/vhosts/mysite.dev/httpdocs/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#21 {main}`

**Comment by eileenmcnaughton** [comment]
one of the templates in the extension is causing a problem - perhaps fully uninstalling & re-intalling it would figure it out'?

**Comment by Firefly0101** [comment]
That worked. Thanks!

**Comment by eileenmcnaughton** [comment]
yay
