### ISSUE TITLE
extendedreports disabled view criteria/results option in regular reports

### ISSUE THREAD

**Issue by magnolia61** [eileenmcnaughton/nz.co.fuzion.extendedreport#43]
Having extendedreport enabled on 4.7.2 (upgraded from 4.6.9) causes by installation to NOT show the 'view result' / 'view criteria' option in the access tab of regular (core) civicrm reports.

The strange thing is that /templates/CRM/Report/Form/Tabs has the proper line for the option
<td>{$form.is_navigation.html} {ts}Link to {/ts}  {$form.view_mode.html}<br />

No clue what causes this but I thought you'd appreciate to know :-)

**Comment by eileenmcnaughton** [comment]
I just pushed a fix that I think will fix it

**Comment by eileenmcnaughton** [comment]
closing since no news is good news - should be fixed
