### ISSUE TITLE
Reports join with all custom tables of given type

### ISSUE THREAD

**Issue by lcdservices** [eileenmcnaughton/nz.co.fuzion.extendedreport#431]
When running the line item report we found that the line total was multiple times the actual amount. Upon reviewing the raw SQL I saw that all of the contact and contribution custom tables were included as left joins -- even though we were not displaying or filtering on any of them.

This was the result of this commit:
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/commit/d45e2c4fd9638e6d27d01a1e04cf2771f1afbef0

It changed the logic for whether a custom table should be joined to the query. The previous logic only joined if the table itself was in use (i.e. a field was selected, where'd, grouped, or ordered). With this commit it now joins all custom tables for which the table they extend is in use. Which pretty much means all contact custom tables will be joined, and in the case of a financial report, all contribution custom tables. Apart from making the queries much longer and less performant, it also can introduce some odd data issues, which is what we saw.

**Comment by lcdservices** [comment]
here's a PR to revert that condition change:
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/432

I'm pretty sure this is what we want to do...

**Comment by eileenmcnaughton** [comment]
I merged a variant of yours. Your PR made it easy to find the line very quickly but it caused a test fail - it turned out checking for prefix fixed that (& the real bug in some reports) - thanks!
