### ISSUE TITLE
Include frequency_interval in CRM_Extendedreport_Form_Report_Contribute_Contributions report

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#435]
In the civicrm_contribution_recur table there is frequency_interval column. Can this be included in CRM_Extendedreport_Form_Report_Contribute_Contributions report?

**Comment by eileenmcnaughton** [comment]
I'd be open to a PR on that - but it is possible via search kit

<img width="1051" alt="Screen Shot 2020-11-06 at 10 07 24 AM" src="https://user-images.githubusercontent.com/336308/98296509-e861eb00-2017-11eb-84a7-83722ad76fb3.png">
