### ISSUE TITLE
Report pulls unknown column with zero data

### ISSUE THREAD

**Issue by pkross** [eileenmcnaughton/nz.co.fuzion.extendedreport#44]
It seems to pull the same erroneous data in every one of the contact reports I am running.

**Comment by eileenmcnaughton** [comment]
I don't know what to do here without more information

**Comment by pkross** [comment]
Whatever it was the 2.2 version fixed. That is awesome. Thanks!

**Comment by eileenmcnaughton** [comment]
phew - I was hoping it was in a state to add a release when I did that...
