### ISSUE TITLE
Extended Report - Relationships does not allow display relationship custom fields

### ISSUE THREAD

**Issue by francescbassas** [eileenmcnaughton/nz.co.fuzion.extendedreport#46]
Hi Eileen,

We are trying to obtain an extended relationship report with relationship custom fields and as we currently can not do. There is a simple way to integrate this missing functionality?

If it's simple and you can guide me, I could try to implement the functionality myself.

**Comment by eileenmcnaughton** [comment]
I've added it - it's a bit wierd that it's on a separate tab in 4.7 without any ui sugar - but that's because the original efforts to make it possible to re-order the columns needs re-writing to adapt to UI changes in core
