### ISSUE TITLE
Activities Template: Activity Date Does Not Include the Time

### ISSUE THREAD

**Issue by cwagner-medullus** [eileenmcnaughton/nz.co.fuzion.extendedreport#462]
In the Activities template, the Activity Date value does not display the time. In the Developer tab for the report, it appears to be retrieving the activity.activity_date_time field. Is it possible to display the time as part of the date in the report?

**Comment by eileenmcnaughton** [comment]
Will be in next release

**Comment by cwagner-medullus** [comment]
Thank you! Looking forward to it.

**Comment by eileenmcnaughton** [comment]
@cwagner-medullus you can see the patch linked above if you want to apply it yourself - it's just removing one line

**Comment by cwagner-medullus** [comment]
> you can see the patch linked above if you want to apply it yourself - it's just removing one line

Thanks, Eileen! That worked perfectly.
