### ISSUE TITLE
New report creation only shows Pivot table and Filters, no columns

### ISSUE THREAD

**Issue by danaskallman** [eileenmcnaughton/nz.co.fuzion.extendedreport#47]
I have been having sporadic issues when enabling an this extension across sites. In all cases it's WordPress and using the latest LTS version of CiviCRM, currently WordPress 4.4.2 and CiviCRM 4.6.14.

After I enable and go to create a new report from template using the only options at the top are Pivot table and Filters, there is no Columns option to select what to include in the report. Here's a screenshot example

![er-missing-columns](https://cloud.githubusercontent.com/assets/1139085/13640389/6ec487a4-e5e2-11e5-9214-c69cdfb4579a.png)

Thoughts on why this would happen?

**Comment by samuelsov** [comment]
Same problem here with Drupal and CiviCRM 4.6 and the latest 2.1 version of the extension.
Version 2.0 seems to work fine.

**Comment by eileenmcnaughton** [comment]
I'm pretty sure this was solved a while back. I have the latest master on 4.7 in front of me & it's all good. I believe it was fixed before the last extension release.

I have now dropped support for legacy versions (4.4 & 4.6) & am only supporting 4.7 but I'm pretty sure there is already a released version working with those versions
