### ISSUE TITLE
CRM_Extendedreport_Form_Report_Price_Lineitemparticipant missing phone entity

### ISSUE THREAD

**Issue by andyburnsco** [eileenmcnaughton/nz.co.fuzion.extendedreport#476]
Seems to have everything else. Ref: https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/1

`CRM_Extendedreport_Form_Report_Price_Lineitemparticipant`

**Comment by eileenmcnaughton** [comment]
I haven't actually tested ^^ but I expect it is all that is needed (& it didn't break the tests)
