### ISSUE TITLE
State/Province as abbreviation

### ISSUE THREAD

**Issue by laryn** [eileenmcnaughton/nz.co.fuzion.extendedreport#489]
Right now the State/Province value comes in as a full name -- we'd prefer it to be the abbreviation. Would you accept a PR to convert that to produce the abbreviation instead, or to add a new "State/Province abbreviation" option in the address columns?

**Comment by Upperholme** [comment]
Please make it optional. As I understand it abbreviations for State/Province names are commonly used in the Us, for example, but that isn't the case elsewhere.

**Comment by laryn** [comment]
Makes sense to me. The question then becomes whether/how to make it an option. A second field listed under Columns > Address? An option under the "Display Options" tab?

In the meantime, I can pretty quickly hack this line:

 - https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/master/CRM/Extendedreport/Form/Report/ExtendedReport.php#L6609

Changing:

`$states = CRM_Core_PseudoConstant::stateProvince($value, FALSE);`

to become:

`$states = CRM_Core_PseudoConstant::stateProvinceAbbreviation($value, FALSE);`
