### ISSUE TITLE
Extended Report - Price Set Line Items

### ISSUE THREAD

**Issue by ryeradio** [eileenmcnaughton/nz.co.fuzion.extendedreport#49]
When I pull the Price Set Line Items report I am trying to get a rollup of Participant Fee Level and the total amount and total number of registrations. I choose the participant count field and currently I am getting zero for most of the line items. Is this the right field to use or is there another field to get the number of registrations per fee level?

I have identified the reason the participant count did not work is because I did not have that filled in on my price sets. Now that I updated that it is closer, but it is still off. I have my event set to allow multiple registrations. If someone registers another person, that person is not showing on the report. Do you know why that might be? For example Bob registered for himself and Sally. Bob is on the report and Sally is not. But technically they are both registered and paid for.

**Comment by eileenmcnaughton** [comment]
I'm going to close this out because it is a support request that is probably no longer relevant. It's not a clear bug or feature request
