### ISSUE TITLE
Filters missing

### ISSUE THREAD

**Issue by chriscant** [eileenmcnaughton/nz.co.fuzion.extendedreport#492]
We've recently wanted to amend an Extended Report and have found that the Filters section is blank (and consequently various JS console errors occur) - see below. This is under WordPress; the same happens on a test site with a simpler configuration.

As far as I can see in CRM/Extendedreport/Form/Report/ExtendedReport.php around line 1320 $filterGroups is not now being filled with the correct info for later display in core Filters.tpl. I've tried adding $filterGroups[$table]['tables'] with some elements but not got it right yet.

This used to work, but I can't remember when I last used it. I think it applies to all extended report. Is anyone else seeing this? If so, help on a fix would be great, thanks.

PS In this extension and in core there are several reference to use_accordian_for_field_selection with an A which should in fact be use_accordion_for_field_selection with an O. In ExtendedReport.php this is currently being set TRUE at line 1316, while FALSE is probably better.

![image](https://user-images.githubusercontent.com/1153272/133247379-3289f357-6824-48f0-9f21-b3894b90021a.png)

**Comment by eileenmcnaughton** [comment]
what version of reports & civi?

**Comment by chriscant** [comment]
Sorry should have said: should be the latest:
CiviCRM 5.41.0. ExtendedReport: Version 5.10

**Comment by IowaBoy1** [comment]
We just updated civi to 5.41.0 last night and have this same problem. It is only with reports that are from Extended Reports, the basic civi reports have Filters.
We are using Drupal 7.82

**Comment by gah242s** [comment]
Additionally seeing this with WP 5.8.1.  Mind posting what kind of console errors are popping up?

**Comment by gah242s** [comment]
Manually deploying the patches from PR #490 looks like it takes care of it, at least on the surface.

**Comment by chriscant** [comment]
Putting those changes in place does fix this issue for me - apologies I should have looked there.
And the accordion spelling is right too :-)
No console errors now.
I'll close but do re-open if need be.
Thanks.

**Comment by eileenmcnaughton** [comment]
Argh - I didn't realise that wasn't merged. I've merged it now despite the test fails & will drop a release to get it out

**Comment by chriscant** [comment]
Thanks

**Comment by IowaBoy1** [comment]
Yes, that fixed it for me as well. Thanks!
