### ISSUE TITLE
 Extended Report - Activities: re-order "columnns"

### ISSUE THREAD

**Issue by masetto** [eileenmcnaughton/nz.co.fuzion.extendedreport#505]
Hi,
please note that this is the first time I have used this extension. :-)

If I this this order columns:
![image](https://user-images.githubusercontent.com/9961202/157415811-bdfb99ae-77bd-45ee-baeb-70fd4fcc43ef.png)

The report does not match
![image](https://user-images.githubusercontent.com/9961202/157415981-c340acf7-2ef3-4810-b318-f32c958b41f4.png)

ps: typo for "column**n**s"

**Comment by eileenmcnaughton** [comment]
Just a quick FYI - I'm personally moving away from this extension & focussing on search kit - there are still some things search kit can't do so it still has it's uses but I'm less actively working on this now

**Comment by masetto** [comment]
I understand and can't disagree with you.
I have tried to use Seark Kit and it is really great. 
I didn't understand if there is a possibility to put the form in the menu without using direct url in the navigation menu.

I think I can close this issue.
