### ISSUE TITLE
Extension database upgrade error

### ISSUE THREAD

**Issue by robbrandt** [eileenmcnaughton/nz.co.fuzion.extendedreport#523]
This week I am working on a long overdue upgrade of a CiviCRM site from 5.13.x to the current version.  When I try to upgrade ExtendedReport, I get the error:

DB_DataObject Error: update: trying to perform an update without the key set, and argument to update is not DB_DATAOBJECT_WHEREADD_ONLY Array ( [seq] => Array ( [0] => id [1] => 1 ) [keys] => Array ( [0] => id ) ) 

Suggestions?

**Comment by eileenmcnaughton** [comment]
Hmm Your extended reports version needs to be appropriate to the Civi version as you get past the civigrant conversion - what version of extended reports codebase do you have?

**Comment by RedBlueBulb** [comment]
I've just got the same error upgrading to 5.18 (on Civi 5.51.3)
