### ISSUE TITLE
problem with "Extended Reports - Participant" report display: Argument 1 passed to CRM_Extendedreport_Form_Report_ExtendedReport::commaSeparateCustomValues() must be of the type string, null given

### ISSUE THREAD

**Issue by catconner** [eileenmcnaughton/nz.co.fuzion.extendedreport#536]
Hi, I've happily used this great extension for years, but have now come across an error I don't know how to solve :-(

Reports based on the template "Extended Reports - Participant" are now sometimes throwing the following error:

`Argument 1 passed to CRM_Extendedreport_Form_Report_ExtendedReport::commaSeparateCustomValues() must be of the type string, null given, called in /DOCROOT/civicrm_custom/extensions/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php on line 2711`

From looking at the code, and functional testing, it seems the issue is with the display side of the report -- and seems to be related only to displaying custom data fields. If certain custom fields, or a combination of custom fields, are selected under the "Columns" tab, the above error appears.

What I've observed so far:

-- This only seems to be affecting the "Extended Reports - Participant" reports. The other core reports and Extended Reports can display custom fields without an issue.
-- Filters on custom data fields seem to be working fine, as long as the offending data fields aren't selected as display columns.
-- The problem is frustratingly intermittent -- It seems that occasionally I randomly stumble on some constellation of report settings that allow the report to work, but I have not yet found any pattern. Could this mean the values of the fields themselves are causing an issue?

Would love some insight, tearing my hair out here ! :-D

System details:
Joomla 3.10.11
CiviCRM 5.55.2
Extended Reports extension 5.18

**Comment by eileenmcnaughton** [comment]
It looks like this was fixed in https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/528 - although I don't appear to have tagged 5.19 yet so only people who grabbed master would have it

**Comment by eileenmcnaughton** [comment]
released

**Comment by catconner** [comment]
Oh! I'm sorry my search didn't turn that up, color me embarrassed.  Thank you for the quick response!
