### ISSUE TITLE
Regression: PR #529 causes Afform tabs to show up in "Manage Events".

### ISSUE THREAD

**Issue by MegaphoneJon** [eileenmcnaughton/nz.co.fuzion.extendedreport#538]
@colemanw @eileenmcnaughton https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/529 introduces an interesting regression.  This is on 5.57.1.

"Summary and Tab: Events by type" is an Afform on this site which adds a new tab to contact records (with an SK query).

With PR #529 applied, it appears in my "Manage Events" screen as an event. 

My "Manage Events" page without PR #529:

![Selection_1747](https://user-images.githubusercontent.com/1796012/212750583-57ce9fce-ce35-4b26-9259-f719ef7c331b.png)

My "Manage Events" page *with* PR #529:
![Selection_1746](https://user-images.githubusercontent.com/1796012/212750669-9608c79d-d906-4a4c-a861-185515722444.png)

**Comment by eileenmcnaughton** [comment]
Did the commit I just merged fix this?

**Comment by colemanw** [comment]
@eileenmcnaughton yea #554 was to fix this
