### ISSUE TITLE
Error from Extended Report - Line item Report (based on contributions)

### ISSUE THREAD

**Issue by adixon** [eileenmcnaughton/nz.co.fuzion.extendedreport#546]
This error started likely due to a recent CiviCRM upgrade. I tried updating this extension to the latest version, and even the current git master, but getting the same error:

`TypeError: Argument 1 passed to CRM_Extendedreport_Form_Report_ExtendedReport::alterPaymentType() must be of the type int or null, string given, called in /var/www/drupal/web/sites/default/files/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php on line 2361 in CRM_Extendedreport_Form_Report_ExtendedReport->alterPaymentType() (line 6521 of /var/www/drupal/web/sites/default/files/civicrm/ext/nz.co.fuzion.extendedreport/CRM/Extendedreport/Form/Report/ExtendedReport.php) `

The alterPaymentType (as well as the alterPaymentProcessor) methods both want a type int or null, but they're getting a blank string instead. I presume that blank string is expected to be null, I'll try unsetting value if it's empty.

**Comment by adixon** [comment]
Yes, that works. In most cases, I'd imagine that the alter function doesn't even need to be called, but I suppose it's possible that an alter function could intentionally do something useful on a null value.

**Comment by eileenmcnaughton** [comment]
I'm pretty sure it doesn't do anything on an empty string

**Comment by adixon** [comment]
A version of this issue has recurred with the latest release.

I can see you're now testing for empty strings there, the error I'm getting is due to a string "1" being passed in as the argument to alterPaymentType.

CiviCRM 5.67.3

**Comment by adixon** [comment]
And another new version of this issue! This time, the error is again in the alterPaymentType, but it's getting a string of "1,5", which is because the report I'm looking at is aggregating line items.

I'm not convinced what the real source of the issue is, but I've got a PR to (re)start a conversation.
