### ISSUE TITLE
Advanced Report configuration page unrendered code

### ISSUE THREAD

**Issue by ecoseeker** [eileenmcnaughton/nz.co.fuzion.extendedreport#550]
When creating a new contact pivot report, when I click on the "Advanced Report configuration" link which "provides options to re-order columnns, change titles & fallback to another field on empty" I see what looks like unrendered code - see attached.

I'm very interested in the "fallback to another field on empty" functionality.

Thanks!

![Screenshot 2023-03-02 at 12-01-15 CiviCRM ‹ Landworkers Alliance — WordPress](https://user-images.githubusercontent.com/219108/222424294-fc46cdda-c55f-4461-95d3-954a3c18fc34.png)

**Comment by eileenmcnaughton** [comment]
Oh that's a pain - have you tried doing it in SearchKit? I'm still maintaining Extended Reports but I think it's close to obsolete as I dont think there is much it does that SearchKit doesn't
