### ISSUE TITLE
Advanced Report configuration shows Unknown path

### ISSUE THREAD

**Issue by kenorb** [eileenmcnaughton/nz.co.fuzion.extendedreport#555]
While on Report instance (/civicrm/report/instance/123?reset=1), I'm following _Advanced Report configuration_ link which shows me the error _Unknown path_. URL: /civicrm/a#/exreport/report/123

- Related code: https://github.com/search?q=repo%3Aeileenmcnaughton%2Fnz.co.fuzion.extendedreport%20exreport&type=code
- Related issue: GH-221

Is this page still exists?

Version: 5.21

**Comment by kenorb** [comment]
Not sure if it's related, but is this typo?

```
$scope.classicUrl = crmLegacy.url('civicrm/report/instance/' + reportInstance.id, 'reset=1output=html');
```

Shouldn't be: reset=1&output=html (with & separator).

See: https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/blob/5.21/ang/extendedreport/ReportCntrl.js#L40

**Comment by kenorb** [comment]
I've looked and extendedreport doesn't appear in Angular list of modules `composer exec cv ang:module:list`.

And it doesn't define `hook_civicrm_angularModules()` anywhere, is this expected?

**Comment by kenorb** [comment]
Ok, it seems I'm still using  5.44.0 CiviCRM and the extension is no longer compatible with it starting from 5.15 as per cfbb586316676f182e3a8ae724d322c4a9799a0f.

**Comment by eileenmcnaughton** [comment]
If you are really stuck you could copy the mixin files in - they are pretty much the same in every extension

**Comment by eileenmcnaughton** [comment]
(I mean they don't all have the same files, but the files they DO have are interchangeable)
