### ISSUE TITLE
Unable to create report from template in 4.7

### ISSUE THREAD

**Issue by litespeedmarc** [eileenmcnaughton/nz.co.fuzion.extendedreport#60]
Am I missing something?  Can't seem to be able to create a custom report in CiviCRM 4.7.  Works fine in 4.6 ("Create Report" button appears). 

**4.6 View:**
![screen shot 2016-07-25 at 12 24 35 am](https://cloud.githubusercontent.com/assets/3502819/17090415/4b19f18a-51fe-11e6-87b9-eb85a3d7c2b9.png)

**In 4.7 screen layout's changed:**
![screen shot 2016-07-25 at 12 26 25 am](https://cloud.githubusercontent.com/assets/3502819/17090438/79c373f8-51fe-11e6-9ecb-140faaa10152.png)

I suspect CiviCRM 4.7 improvements on 'report template actions' has something to do with it
![screen shot 2016-07-25 at 12 27 39 am](https://cloud.githubusercontent.com/assets/3502819/17090462/b0da8aa2-51fe-11e6-9ce9-982b829852fe.png)

I don't mind investigating a fix, but before I get too deep into this, seems like someone should have ran into this already.

**Comment by eileenmcnaughton** [comment]
I think there is a fix in the latest master - added recently

**Comment by litespeedmarc** [comment]
You're right.  Thanks.  

Seems wherever 4.7 CiviCRM extensions "add new" points to, doesn't point to the latest & greatest.

**Comment by eileenmcnaughton** [comment]
I'll tag a new release soon - I just merged a couple of other changes & thought I'd let them sit for a few days in case of any probs
