### ISSUE TITLE
Actions Area missing

### ISSUE THREAD

**Issue by sleewok** [eileenmcnaughton/nz.co.fuzion.extendedreport#61]
I can preview reports just fine, but the actions drop down is missing. I am unable to perform any actions on the reports when creating from a template. 

I'm using the version installed from within CiviCRM (4.7.9)

**Comment by eileenmcnaughton** [comment]
I've tagged 2.4 so it should be available though the UI soon

**Comment by sleewok** [comment]
Excellent. Thanks!

**Comment by eileenmcnaughton** [comment]
Closing as I'm pretty sure this is OK against the latest version
