### ISSUE TITLE
contrib detail template errors

### ISSUE THREAD

**Issue by lcdservices** [eileenmcnaughton/nz.co.fuzion.extendedreport#65]
Call to undefined method CRM_Extendedreport_Form_Report_Contribute_DetailExtended::extendedCustomDataFrom()

**Comment by lcdservices** [comment]
https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/pull/66

**Comment by eileenmcnaughton** [comment]
Looks like you provided a fix for this which I merged some time back. Closing
