### ISSUE TITLE
2.5 released?

### ISSUE THREAD

**Issue by twomice** [eileenmcnaughton/nz.co.fuzion.extendedreport#69]
I see there's a tag "2.5", but the c.o extension page only lists up to 2.4 (https://civicrm.org/extensions/extended-reports). Problem with the auto-release system on c.o?

**Comment by eileenmcnaughton** [comment]
looks like the tag was wrong - hopefully it will do it now

**Comment by PalanteJon** [comment]
This is fixed and OK to close.
