### ISSUE TITLE
Permissions error in Joomla!

### ISSUE THREAD

**Issue by twomice** [eileenmcnaughton/nz.co.fuzion.extendedreport#70]
(Note correction in https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/70#issuecomment-256095923)

Upon installing this extension under Joomla!, CiviCRM reports this error:

> Some modules define permissions, but the CMS cannot store them: extendedreport

As such, this extension then provides no new reports at all, because nobody has this (now nonexistent) permission.

This appears to be caused by https://issues.civicrm.org/jira/browse/CRM-12059, "Support hook_civicrm_permissions on Joomla", which seems to have stalled for lack of attention from a Joomla! developer.  

However, I think this extension could be modified to bypass the problem, by using a civicrm core permission ("administer CiviCRM" if nothing else) instead of its own custom permission, where the CMS is Joomla!  This could be detected with `CRM_Core_Config::singleton()->userPermissionClass->isModulePermissionSupported()`, as is done to slightly different effect by CiviVolunteer (see
https://forum.civicrm.org/index.php?topic=33396.msg143854#msg143854 and https://github.com/civicrm/org.civicrm.volunteer/pull/201/files#diff-6a375959edd3964f4cd18caed7426a66R104)

Whatcha think?

**Comment by eileenmcnaughton** [comment]
This extension perhaps doesn't need to define a permission anymore.

The permission it defines is 'access CiviCRM report developer' - but there is now (4.6 or 4.7 ?) a permission in core that has the same meaning so there is no reason to have this in the extension now. Arguably for backwards compatibility but perhaps if the extension didn't exist & wasn't assigned the developer tab (now in core) would not display and the world would not end, or at least only slowly.

**Comment by twomice** [comment]
Correction: I'm looking at this same site now under CiviCRM 4.7.12, and find that the reports I'm expecting to see are indeed available. So the title, "... breaks extension ..." is not accurate.

However, the error message still appears, and could probably be dealt with in the ways @eileenmcnaughton describes above.

**Comment by twomice** [comment]
Amending title according to my previous comment (https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/70#issuecomment-256095923)

**Comment by eileenmcnaughton** [comment]
I have removed the code causing the problem. The issue was caused by code overrides making 4.7 functionality available to previous versions. I have just discontinued support for previous versions (next release will support 4.7 only but 4.4. & 4.6 can continue to use already published releases) so I can fix the bug and simplify the code base by just removing code.
