### ISSUE TITLE
In Flexible Contact Report, Subtype field does not work

### ISSUE THREAD

**Issue by hoegrammer** [eileenmcnaughton/nz.co.fuzion.extendedreport#75]
The Contact Subtype field in the filter does not let you pick subtypes. It seems that it is a duplicate of the field above.

**Comment by eileenmcnaughton** [comment]
patch fixes it for me. Note that I have just stopped supporting 4.4 & 4.6 for future releases of this extension (previous releases will continue to work on them) and the patch may or may not work on those core versions
