### ISSUE TITLE
Contribution Line Item Report displaying Summary as duplicated last row

### ISSUE THREAD

**Issue by zkrebs** [eileenmcnaughton/nz.co.fuzion.extendedreport#81]
![screenshot 2017-01-06 at 10 13 02 am](https://cloud.githubusercontent.com/assets/366418/21727996/d45fe91e-d3f8-11e6-8272-8cbc113a0e2b.png)

Why is this happening? Doesn't seem to be there when exporting report to Excel.

**Comment by eileenmcnaughton** [comment]
Is that on the latest code from github?

**Comment by zkrebs** [comment]
Its Extended Report 2.5 downloaded via CiviCRM 4.6.23

**Comment by eileenmcnaughton** [comment]
Hmm - I have done some work on extended report recently that might change it - but I also discontinued supporting versions prior to 4.7 & I don't expect it will work on 4.6 now

**Comment by zkrebs** [comment]
OK, I was planning an update to 4.7 so I will report back and close this once its done. Guess no need to fix?

**Comment by eileenmcnaughton** [comment]
let me know if the latest from github works better once you are on 4.7

**Comment by zkrebs** [comment]
I updated to 4.7 and I am seeing a similar issue on a different report

The last line of the report appears to concatenate all of the prior lines into the row.

So if I had

Name    City           Unit Price     Total of Line Items
A           Eugene      1                   100.00
B           Ashland      100.              100.00
C           Portland      5                   5.00

The last row is:
A,B,C   Eugene, Ashland, Portland   1,100,5       100.00,100.00, 5.00

This is for a Line Item Contribution Report.
I'm also noticing the columns in the report are ridiculously wide.

**Comment by eileenmcnaughton** [comment]
So the rows are OK except there is an additional roll-up row that is pretty confusing?

**Comment by zkrebs** [comment]
They are OK except for the formatting issue. Why is there so much whitespace?

And yes, the roll-up row confuses my coworker, because its not clearly marked, and can be interpreted as one of the results. Is that by design?

**Comment by eileenmcnaughton** [comment]
no - it should not show like that. Is it not the last row making the others wide?

**Comment by zkrebs** [comment]
Good catch! When I display:none on the last row it solves the layout issue.

Is there any user configurable setting I can do to fix this report? Or is it a bug?

**Comment by eileenmcnaughton** [comment]
it's a bug - I'll try to get to it. I do need to do some reporting work soon

**Comment by zkrebs** [comment]
Thanks @eileenmcnaughton the module rules, couldn't live without it. Let us know if you have a chip-in/donation tool.

**Comment by zkrebs** [comment]
I updated to 2.9 and the issue remains. Is there any easy fix I could do in the interim?

**Comment by eileenmcnaughton** [comment]
I just tried to replicate it & failed. I have just tagged release 3.0 and I note there is a fix in there by @jitendrapurohit that might relate. 

If you still hit this on 3.0 can you paste the contents of the developer tab?

**Comment by zkrebs** [comment]
I am using 3.0 and the issue is still present.

Do you want the HTML output of the whole page? There are no JS errors in console.

**Comment by zkrebs** [comment]
Oh, this 

`Class used: CRM_Extendedreport_Form_Report_Price_Contributionbased

SELECT SQL_CALC_FOUND_ROWS GROUP_CONCAT(DISTINCT civicrm_contact.first_name) as civicrm_contact_civicrm_contact_first_name, GROUP_CONCAT(DISTINCT civicrm_contact.last_name) as civicrm_contact_civicrm_contact_last_name, GROUP_CONCAT(DISTINCT contribution.source) as civicrm_contribution_contribution_source, GROUP_CONCAT(DISTINCT contribution.receive_date) as civicrm_contribution_contribution_receive_date, GROUP_CONCAT(DISTINCT price_field.label) as civicrm_price_field_price_field_price_field_label, GROUP_CONCAT(DISTINCT price_field_value.label) as civicrm_price_field_value_price_field_value_label, GROUP_CONCAT(DISTINCT line_item.financial_type_id) as civicrm_line_item_line_item_financial_type_id, GROUP_CONCAT(DISTINCT line_item.unit_price) as civicrm_line_item_line_item_unit_price, sum(line_item.line_total) as civicrm_line_item_line_item_line_total_sum  

FROM civicrm_contribution contribution
      
  LEFT JOIN civicrm_line_item as line_item
      ON line_item.contribution_id = contribution.id
     
  LEFT JOIN civicrm_contact civicrm_contact
ON contribution.contact_id = civicrm_contact.id 
  LEFT JOIN civicrm_price_field_value price_field_value
ON line_item.price_field_value_id = price_field_value.id

  LEFT JOIN civicrm_price_field price_field
ON line_item.price_field_id = price_field.id
 
  LEFT JOIN civicrm_address address
    ON address.contact_id = civicrm_contact.id
    AND address.is_primary = 1
     

WHERE ( contribution.contribution_status_id IN (1) ) AND ( contribution.receive_date >= '20161114000000') AND ( contribution.receive_date <= '20170130235959' ) AND ( line_item.financial_type_id IN (27) ) AND civicrm_contact.is_deleted = 0  

GROUP BY contribution.id  WITH ROLLUP   `

**Comment by zkrebs** [comment]
Is there anything else I can provide to assist with this debugging?

**Comment by jitendrapurohit** [comment]
@zkrebs Added fix for the issue mentioned here at https://github.com/eileenmcnaughton/nz.co.fuzion.extendedreport/issues/98. Can you verify if it works for you?

**Comment by eileenmcnaughton** [comment]
I think this is fixed

**Comment by zkrebs** [comment]
I will try it tomorrow and report back, thanks.
