### ISSUE TITLE
Custom Fields not showing on Activities, includes multi-contact custom fields

### ISSUE THREAD

**Issue by gah242s** [eileenmcnaughton/nz.co.fuzion.extendedreport#83]
After upgrading to CiviCRM 4.7.16 and ExtendedReports 2.7 on a WordPress install, custom fields are not showing in the resulting report.  They are activities filtered on a custom type and a status of scheduled, displayed by Target Contact ::Contact Name (in sort format).  The contact names, show up, but not the custom fields associated with the activity.  I have recreated the report from scratch and gotten the same results.  I can show multiple different related activity attributes that are shown in the Column tab, but the custom fields do not show up.  This report worked on CiviCRM 4.7.15 and ExtendedReports 2.6.

**Comment by eileenmcnaughton** [comment]
I have pushed a fix for this - please confirm & I will close & increment the version released so people get the fixed version

**Comment by gah242s** [comment]
Well, doesn't that look purty!  Thanks Eileen!  It's rather amazing everything you are keeping up with and tracking down.  Thanks for the hard work.
