### ISSUE TITLE
Unable to Preview Relationships report when include a group in the filters

### ISSUE THREAD

**Issue by kngs** [eileenmcnaughton/nz.co.fuzion.extendedreport#85]
I am unable to save the Relationships Extended Report when I include a group in the filters.  I get the following message:

 Sorry but we are not able to provide this at the moment.
DB Error: syntax error
Return to home page.

P.S.  I also noticed that when I include a custom field in the display columns, it does not appear. 
I also get the same error message above if I try and filter on a custom field as noted in another Issue.

Thanks!

**Comment by agileware** [comment]
Hi,

We've experienced this issue as well. Don't have a fix at this stage
Ref: SUP-1711

**Comment by eileenmcnaughton** [comment]
I've just pushed a fix  - hopefully it works

**Comment by eileenmcnaughton** [comment]
Am closing on the assumption the fix worked - please let me know if not
