### ISSUE TITLE
filter by activity target in the ActivityExtended report

### ISSUE THREAD

**Issue by jmcclelland** [eileenmcnaughton/nz.co.fuzion.extendedreport#89]
In the ActivityExtended report you can display activity source, target or assigned contacts.

However, you can only filter by the Activity Source.

I noticed in the code that this limitation seems to be set fairly explicitly with a big ole "FALSE"...

      public function __construct() {
    $this->_columns = $this->getColumns(
      'Contact',
      array(
        'prefix' => '',
        'prefix_label' => 'Source Contact ::',
        'filters' => TRUE,
      )
    ) + $this->getColumns(
        'Contact',
        array(
          'prefix' => 'target_',
          'group_by' => TRUE,
          'prefix_label' => 'Target Contact ::',
          'filters' => FALSE,
        )
    )

However, in my dev instance I switched it to TRUE and it worked - both filtering by source and by target and by both seemed to work.

Is this disabled for a reason that I may be missing?

**Comment by eileenmcnaughton** [comment]
Go ahead & change it - a lot of these reports started from other reports

**Comment by jmcclelland** [comment]
Great! Thanks for the feedback. Just created a PR.

**Comment by eileenmcnaughton** [comment]
this was fixed in linked PR
