### ISSUE TITLE
Line item financial types not displaying in Line Item - Time Filter reports

### ISSUE THREAD

**Issue by joannechester** [eileenmcnaughton/nz.co.fuzion.extendedreport#91]
I have a report that should show just **Line item financial type** and **total of line items** grouped by **Line item financial type** .

This two columns are indeed what I see if I don't apply any grouping, but when I group by **Line item financial type** the only column that is displayed it **total of line items** even though the **Line item financial type**  is selected on the Columns tab.

Same thing happens if I base the report on **Extended Report - Price Set Line Items**  or **Extended Report - Contributions with Price Set data** 

(BTW, the totals are correct and grouping by any other field seems to display correctly.)

**Comment by eileenmcnaughton** [comment]
@joannechester is this fixed now?

**Comment by joannechester** [comment]
Yes this is fixed now

**Comment by eileenmcnaughton** [comment]
thanks
