### ISSUE TITLE
Sort by Receive Date - Line item report (based on contributions)

### ISSUE THREAD

**Issue by IowaBoy1** [eileenmcnaughton/nz.co.fuzion.extendedreport#96]
It would be very helpful for generating a bookkeeping report with line item info, if we could Sort by Receive Date. Is this possible in a future update? Or is there a simple way for me to edit the template so it does it for us?

**Comment by eileenmcnaughton** [comment]
Good timing - I was just working on the report - have pushed up a fix

**Comment by IowaBoy1** [comment]
Thanks so much!!! That is helps a ton.
