### ISSUE TITLE
Test transactions can't be excluded

### ISSUE THREAD

**Issue by joannechester** [eileenmcnaughton/nz.co.fuzion.extendedreport#99]
I thought the line item report had the ability to filter out test transactions, but it isn't there now. Until 4 months ago we were on Civi 4.4 and so were possibly using an older version of this extension.

This would be the first time we have test transactions since the upgrade.

I know test transactions were not included in the precursor to this report ( Eileen, see Fuzion issue 2890), and I am sure they could be excluded in earlier version of this extension.   

Is it possible to have a filter added so that test transactions can be excluded.

**Comment by eileenmcnaughton** [comment]
Added a fix

**Comment by eileenmcnaughton** [comment]
closing - I think this must be fine now
